export const artists = [
  {
    id: 1,
    name: "范汇飞",
    bio: "青年油画艺术家，作品多聚焦花卉与自然景观，以鲜活色彩和细腻笔触呈现四时生机。",
    avatar: "/artists/fanhuifei/范汇飞《窗前的海棠花》50x60cm 2025年.jpg",
    location: "中国",
    followers: 1860,
    works: 19,
  },
  {
    id: 2,
    name: "郭争光",
    bio: "1980年生于龙岩，福建师范大学艺术硕士，福建幼儿师范高等专科学校美术教研室主任、副教授，中国美术家协会会员，擅长以民居与城镇景观书写在地记忆。",
    avatar: "/artists/guozhengguang/郭争光生活照.jpg",
    location: "福建龙岩",
    followers: 4280,
    works: 17,
  },
  {
    id: 3,
    name: "侯虹旭",
    bio: "上海美术家协会会员，毕业于山东大学与华东师范大学美术系，现工作生活于北京，创作关注都市语境与日常景观中的情感距离。",
    avatar: "/artists/houhongxu/侯虹旭《远方》 50×70cm 布面油画 2021年.jpg",
    location: "北京",
    followers: 2960,
    works: 10,
  },
  {
    id: 4,
    name: "戢佳",
    bio: "笔名戢茹嘉，四川省美术家协会会员，长期深耕写意油画创作，作品多次入选全国性展览并获奖。",
    avatar: "/artists/jijia/一、戢佳《白石清风》60x60cm 布面油画 2025年.jpg",
    location: "四川成都",
    followers: 3920,
    works: 21,
  },
  {
    id: 5,
    name: "刘传珂",
    bio: "油画艺术家，擅长以花卉与自然景致入画，画面兼具抒情气息与柔和色彩层次。",
    avatar: "/artists/liuchuanke/刘传珂《读花观海》40×50cm 布面油画.jpg",
    location: "中国",
    followers: 1740,
    works: 3,
  },
  {
    id: 6,
    name: "生辉",
    bio: "1978年生于山东东营，山东省美术家协会会员、山东省油画学会理事，北京当代中国写意油画院特约创作员，作品以写意油画语言表现山水与田野气象。",
    avatar: "/artists/shenghui/生辉工作照.jpg",
    location: "山东东营",
    followers: 3650,
    works: 25,
  },
  {
    id: 7,
    name: "吴良孝",
    bio: "油画艺术家，作品围绕山海、花意与静夜景象展开，以厚重笔触和浓烈色彩塑造情绪张力。",
    avatar: "/artists/wuliangxiao/4177a9f54de70f330c44a6b5939afc42.jpg",
    location: "中国",
    followers: 2080,
    works: 2,
  },
  {
    id: 8,
    name: "吴有才",
    bio: "中国美术家协会会员，北京当代中国写意油画研究院特约创作员，海沧区美术家协会副主席，近年持续以“红色记忆”系列与风景作品活跃于全国展览。",
    avatar: "/artists/wuyoucai/一.png",
    location: "福建厦门",
    followers: 4460,
    works: 2,
  },
  {
    id: 9,
    name: "许丙屯",
    bio: "广东徐闻人，中国美术家协会会员、中国油画学会会员，曾获国家艺术基金青年创作资助，作品多次入选全国重要展览并在公益拍卖中获得广泛关注。",
    avatar: "/artists/xubingtun/一、许丙屯《秋日》50×50cm 布面油画 2024年.JPG",
    location: "广东徐闻",
    followers: 5120,
    works: 11,
  },
  {
    id: 10,
    name: "张昆",
    bio: "风景题材艺术家，擅长描绘山林、园林与田园意象，画面色彩丰沛，重视自然气息与诗意栖居的营造。",
    avatar: "/artists/zhangkun/一、园林一角40×40.jpg",
    location: "中国",
    followers: 2310,
    works: 14,
  },
]

export const artworks = [
  {
    id: 1,
    title: "窗前的海棠花",
    aid: 1,
    artist: "范汇飞",
    price: 28000,
    orig: null,
    cat: "油画",
    style: "花卉写意",
    size: "50×60cm",
    year: "2025",
    mat: "布面油画",
    desc: "取景窗前盛放海棠，以温柔笔触描摹花影摇曳的春日气息。",
    img: "/artists/fanhuifei/范汇飞《窗前的海棠花》50x60cm 2025年.jpg",
    views: 1320,
    sold: 0,
    stock: 1,
    featured: true,
    charityPct: 20,
  },
  {
    id: 2,
    title: "艾山烟雨",
    aid: 1,
    artist: "范汇飞",
    price: 36000,
    orig: null,
    cat: "油画",
    style: "风景写意",
    size: "60×80cm",
    year: "2025",
    mat: "布面油画",
    desc: "以湿润柔和的色层表现山岚氤氲，营造静谧而悠长的自然氛围。",
    img: "/artists/fanhuifei/范汇飞《艾山烟雨》60x80cm 2025年.jpg",
    views: 980,
    sold: 0,
    stock: 1,
    featured: false,
    charityPct: 20,
  },
  {
    id: 3,
    title: "湖畔春色",
    aid: 2,
    artist: "郭争光",
    price: 42000,
    orig: null,
    cat: "油画",
    style: "风景油画",
    size: "50×60cm",
    year: "2019",
    mat: "布面油画",
    desc: "湖畔与村舍在明亮色彩中层层铺开，传递春日生机与空间节奏。",
    img: "/artists/guozhengguang/一、郭争光《湖畔春色》50×60cm  布面油画  2019年.jpg",
    views: 1560,
    sold: 0,
    stock: 1,
    featured: true,
    charityPct: 20,
  },
  {
    id: 4,
    title: "乐园",
    aid: 2,
    artist: "郭争光",
    price: 46000,
    orig: null,
    cat: "油画",
    style: "城市景观",
    size: "60×80cm",
    year: "2024",
    mat: "布面油画",
    desc: "将建筑与自然景色交织入画，形成既现实又带梦境感的空间记忆。",
    img: "/artists/guozhengguang/二、郭争光《乐园》60×80cm   布面油画  2024年.jpg",
    views: 1410,
    sold: 0,
    stock: 1,
    featured: false,
    charityPct: 20,
  },
  {
    id: 5,
    title: "石桥人家",
    aid: 2,
    artist: "郭争光",
    price: 39000,
    orig: null,
    cat: "油画",
    style: "人文风景",
    size: "40×80cm",
    year: "2023",
    mat: "布面油画",
    desc: "以石桥、民居与河岸构成画面主线，浓缩闽南生活气息。",
    img: "/artists/guozhengguang/三、郭争光《石桥人家》40×80cm  布面油画  2023年.jpg",
    views: 1210,
    sold: 0,
    stock: 1,
    featured: false,
    charityPct: 20,
  },
  {
    id: 6,
    title: "远方",
    aid: 3,
    artist: "侯虹旭",
    price: 32000,
    orig: null,
    cat: "油画",
    style: "当代绘画",
    size: "50×70cm",
    year: "2021",
    mat: "布面油画",
    desc: "画面以人物与空间的若即若离，折射日常景观中的情绪距离。",
    img: "/artists/houhongxu/侯虹旭《远方》 50×70cm 布面油画 2021年.jpg",
    views: 1280,
    sold: 0,
    stock: 1,
    featured: true,
    charityPct: 20,
  },
  {
    id: 7,
    title: "未来已来",
    aid: 3,
    artist: "侯虹旭",
    price: 34000,
    orig: null,
    cat: "油画",
    style: "当代绘画",
    size: "60×90cm",
    year: "2020",
    mat: "布面油画",
    desc: "以平静却带张力的构图，描绘现代生活中对未来的投射与想象。",
    img: "/artists/houhongxu/侯虹旭《未来已来》60×90cm 布面油画 2020年.jpg",
    views: 1190,
    sold: 0,
    stock: 1,
    featured: false,
    charityPct: 20,
  },
  {
    id: 8,
    title: "白石清风",
    aid: 4,
    artist: "戢佳",
    price: 38000,
    orig: null,
    cat: "油画",
    style: "写意油画",
    size: "60×60cm",
    year: "2025",
    mat: "布面油画",
    desc: "借清朗石景与流动光色，呈现写意油画中沉静而饱满的精神气质。",
    img: "/artists/jijia/一、戢佳《白石清风》60x60cm 布面油画 2025年.jpg",
    views: 1490,
    sold: 0,
    stock: 1,
    featured: true,
    charityPct: 20,
  },
  {
    id: 9,
    title: "借你一扇窗",
    aid: 4,
    artist: "戢佳",
    price: 46000,
    orig: null,
    cat: "油画",
    style: "写意油画",
    size: "120×100cm",
    year: "2023",
    mat: "布面油画",
    desc: "将窗景、光影与内在情绪并置，形成富有叙事感的观看体验。",
    img: "/artists/jijia/二、戢佳《借你一扇窗》120x100cm 布面油画 2023年.jpg",
    views: 1350,
    sold: 0,
    stock: 1,
    featured: false,
    charityPct: 20,
  },
  {
    id: 10,
    title: "枣园秋熟",
    aid: 4,
    artist: "戢佳",
    price: 52000,
    orig: null,
    cat: "油画",
    style: "写意油画",
    size: "100×120cm",
    year: "2024",
    mat: "布面油画",
    desc: "以浓郁暖色捕捉秋日丰收景象，传递土地与季节的厚实力量。",
    img: "/artists/jijia/三、戢佳《枣园秋熟》100x120cm 布面油画 2024年.jpg",
    views: 1180,
    sold: 0,
    stock: 1,
    featured: false,
    charityPct: 20,
  },
  {
    id: 11,
    title: "读花观海",
    aid: 5,
    artist: "刘传珂",
    price: 26000,
    orig: null,
    cat: "油画",
    style: "花卉风景",
    size: "40×50cm",
    year: "2025",
    mat: "布面油画",
    desc: "花影与海意在一幅画中相互映照，色彩轻盈而富于诗意。",
    img: "/artists/liuchuanke/刘传珂《读花观海》40×50cm 布面油画.jpg",
    views: 860,
    sold: 0,
    stock: 1,
    featured: true,
    charityPct: 20,
  },
  {
    id: 12,
    title: "绽放",
    aid: 5,
    artist: "刘传珂",
    price: 22000,
    orig: null,
    cat: "油画",
    style: "花卉油画",
    size: "40×40cm",
    year: "2025",
    mat: "布面油画",
    desc: "以开放姿态的花朵为主体，笔触明快，画面充满春日生长感。",
    img: "/artists/liuchuanke/刘传珂《绽放》40×40cm 布面油画.jpg",
    views: 740,
    sold: 0,
    stock: 1,
    featured: false,
    charityPct: 20,
  },
  {
    id: 13,
    title: "海边",
    aid: 6,
    artist: "生辉",
    price: 36000,
    orig: null,
    cat: "油画",
    style: "写意油画",
    size: "60×80cm",
    year: "2024",
    mat: "布面油画",
    desc: "以开放笔意描绘海边光线与空间起伏，展现自然景观的呼吸感。",
    img: "/artists/shenghui/一、生辉《海边》  60x80cm 布面油画 2024年.jpg",
    views: 1440,
    sold: 0,
    stock: 1,
    featured: true,
    charityPct: 20,
  },
  {
    id: 14,
    title: "山水之梦之八",
    aid: 6,
    artist: "生辉",
    price: 24000,
    orig: null,
    cat: "丙烯油画",
    style: "写意风景",
    size: "50×40cm",
    year: "2025",
    mat: "布面丙烯油画",
    desc: "在梦幻般的山水构成中，探索自然与内心景象的交会。",
    img: "/artists/shenghui/二、生辉《山水之梦之八》  50x40cm 布面丙烯油画 2025年.jpg",
    views: 1120,
    sold: 0,
    stock: 1,
    featured: false,
    charityPct: 20,
  },
  {
    id: 15,
    title: "艺甸园的屋顶",
    aid: 6,
    artist: "生辉",
    price: 36000,
    orig: null,
    cat: "油画",
    style: "写意风景",
    size: "60×80cm",
    year: "2024",
    mat: "布面油画",
    desc: "将屋顶、天空与周边环境化作跳跃色块，形成明快节奏。",
    img: "/artists/shenghui/三、生辉《艺甸园的屋顶》  60x80cm 布面油画 2024年.jpg",
    views: 960,
    sold: 0,
    stock: 1,
    featured: false,
    charityPct: 20,
  },
  {
    id: 16,
    title: "惊涛",
    aid: 7,
    artist: "吴良孝",
    price: 32000,
    orig: null,
    cat: "油画",
    style: "海景表现",
    size: "60×80cm",
    year: "2025",
    mat: "布面油画",
    desc: "以翻涌海浪与厚重肌理构成强烈视觉张力，呈现山海之间的力量感。",
    img: "/artists/wuliangxiao/惊涛60X80cm吴良孝2025年.jpg",
    views: 920,
    sold: 0,
    stock: 1,
    featured: true,
    charityPct: 20,
  },
  {
    id: 17,
    title: "秋意",
    aid: 7,
    artist: "吴良孝",
    price: 28000,
    orig: null,
    cat: "油画",
    style: "抒情风景",
    size: "60×80cm",
    year: "2025",
    mat: "布面油画",
    desc: "用沉静色层描绘秋日景致，在温润笔触中传达季节的内省气息。",
    img: "/artists/wuliangxiao/秋意60X80cm吴良孝2025年.jpg",
    views: 760,
    sold: 0,
    stock: 1,
    featured: false,
    charityPct: 20,
  },
  {
    id: 18,
    title: "红色记忆之一",
    aid: 8,
    artist: "吴有才",
    price: 30000,
    orig: null,
    cat: "油画",
    style: "主题创作",
    size: "—",
    year: "2025",
    mat: "布面绘画",
    desc: "资料中收录的主题作品之一，以厚重色彩和叙事构图延续“红色记忆”系列表达。",
    img: "/artists/wuyoucai/二、.png",
    views: 680,
    sold: 0,
    stock: 1,
    featured: false,
    charityPct: 20,
  },
  {
    id: 19,
    title: "红色记忆之二",
    aid: 8,
    artist: "吴有才",
    price: 30000,
    orig: null,
    cat: "油画",
    style: "主题创作",
    size: "—",
    year: "2025",
    mat: "布面绘画",
    desc: "延续人物与历史叙事表达，画面更强调群像氛围与精神力量。",
    img: "/artists/wuyoucai/三、.png",
    views: 640,
    sold: 0,
    stock: 1,
    featured: false,
    charityPct: 20,
  },
  {
    id: 20,
    title: "秋日",
    aid: 9,
    artist: "许丙屯",
    price: 30000,
    orig: null,
    cat: "油画",
    style: "风景油画",
    size: "50×50cm",
    year: "2024",
    mat: "布面油画",
    desc: "用沉稳而明亮的色调表现秋景层次，画面饱含南方自然气息。",
    img: "/artists/xubingtun/一、许丙屯《秋日》50×50cm 布面油画 2024年.JPG",
    views: 1380,
    sold: 0,
    stock: 1,
    featured: true,
    charityPct: 20,
  },
  {
    id: 19,
    title: "秋荷",
    aid: 9,
    artist: "许丙屯",
    price: 30000,
    orig: null,
    cat: "油画",
    style: "风景油画",
    size: "50×50cm",
    year: "2024",
    mat: "布面油画",
    desc: "以简洁构成与温润色层表现荷塘秋意，安静中见力量。",
    img: "/artists/xubingtun/三、许丙屯《秋荷》50×50cm 布面油画 2024年.JPG",
    views: 920,
    sold: 0,
    stock: 1,
    featured: false,
    charityPct: 20,
  },
  {
    id: 20,
    title: "园林一角",
    aid: 10,
    artist: "张昆",
    price: 26000,
    orig: null,
    cat: "油画",
    style: "风景油画",
    size: "40×40cm",
    year: "2025",
    mat: "布面油画",
    desc: "取园林一隅入画，在细腻层次中传达静观自然的闲适意境。",
    img: "/artists/zhangkun/一、园林一角40×40.jpg",
    views: 870,
    sold: 0,
    stock: 1,
    featured: true,
    charityPct: 20,
  },
  {
    id: 21,
    title: "香韵",
    aid: 10,
    artist: "张昆",
    price: 32000,
    orig: null,
    cat: "油画",
    style: "风景油画",
    size: "60×80cm",
    year: "2025",
    mat: "布面油画",
    desc: "花木与空间在柔和色彩中展开，营造温润而富有诗性的氛围。",
    img: "/artists/zhangkun/二、香韵60×80.jpg",
    views: 790,
    sold: 0,
    stock: 1,
    featured: false,
    charityPct: 20,
  },
  {
    id: 22,
    title: "田园锦绣",
    aid: 10,
    artist: "张昆",
    price: 34000,
    orig: null,
    cat: "油画",
    style: "田园风景",
    size: "60×80cm",
    year: "2025",
    mat: "布面油画",
    desc: "以饱满色彩表现田园景观的明媚与丰盛，富有生活温度。",
    img: "/artists/zhangkun/三、田园锦绣60×80.jpg",
    views: 830,
    sold: 0,
    stock: 1,
    featured: false,
    charityPct: 20,
  },
]

export const categories = ["全部", "国画", "油画", "水彩", "雕塑", "摄影", "陶艺"]

export const categoryIcons = {
  全部: "🌟",
  国画: "🎋",
  油画: "🖼️",
  水彩: "🌈",
  雕塑: "🗿",
  摄影: "📷",
  陶艺: "🏺",
}

export const exhibitions = [
  {
    id: 1,
    title: "春季名家精品展",
    type: "线上展览",
    cover: "https://picsum.photos/seed/ex1/800/500",
    artist: "美芽集合作艺术家",
    location: "线上展厅",
    date: "2026-04-20 至 2026-05-20",
    price: 0,
    status: "正在展出",
    tag: "免费参观",
    desc: "汇聚十位合作艺术家的最新代表作，呈现花卉、风景与写意油画等多元面貌。",
    highlights: ["线上观展", "十位艺术家联展", "代表作品集中呈现"],
  },
  {
    id: 2,
    title: "美育公益联展",
    type: "公益展览",
    cover: "https://picsum.photos/seed/ex2/800/500",
    artist: "美芽集公益计划",
    location: "美芽集公益空间",
    date: "2026-05-01 至 2026-06-01",
    price: 0,
    status: "即将开始",
    tag: "公益主题",
    desc: "围绕公益美育与乡村振兴主题，展示艺术家参与公益项目的创作力量。",
    highlights: ["公益主题策展", "乡村美育内容呈现", "艺术共创交流"],
  },
]

export const orders = [
  {
    id: "MYJ20260408001",
    status: "待发货",
    date: "2026-04-08 14:20",
    total: 64000,
    arts: [
      {
        title: "窗前的海棠花",
        artist: "范汇飞",
        price: 28000,
        img: "/artists/fanhuifei/范汇飞《窗前的海棠花》50x60cm 2025年.jpg",
      },
      {
        title: "乐园",
        artist: "郭争光",
        price: 46000,
        img: "/artists/guozhengguang/二、郭争光《乐园》60×80cm   布面油画  2024年.jpg",
      },
    ],
  },
  {
    id: "MYJ20260402002",
    status: "运输中",
    date: "2026-04-02 09:15",
    total: 38000,
    arts: [
      {
        title: "白石清风",
        artist: "戢佳",
        price: 38000,
        img: "/artists/jijia/一、戢佳《白石清风》60x60cm 布面油画 2025年.jpg",
      },
    ],
  },
  {
    id: "MYJ20260326003",
    status: "已完成",
    date: "2026-03-26 16:48",
    total: 30000,
    arts: [
      {
        title: "秋日",
        artist: "许丙屯",
        price: 30000,
        img: "/artists/xubingtun/一、许丙屯《秋日》50×50cm 布面油画 2024年.JPG",
      },
    ],
  },
]

export const charity = [
  {
    id: 1,
    title: "乡村美育教室计划",
    tag: "长期项目",
    cover: "https://picsum.photos/seed/charity1/800/500",
    desc: "联合艺术家与志愿者，为乡村学校建设可持续运转的美育教室与课程体系。",
    raised: 128000,
    beneficiaries: 180,
  },
  {
    id: 2,
    title: "儿童写生活动支持计划",
    tag: "公益活动",
    cover: "https://picsum.photos/seed/charity2/800/500",
    desc: "为偏远地区儿童提供写生工具包、课程支持与线下艺术体验活动。",
    raised: 86000,
    beneficiaries: 96,
  },
]

export const stories = [
  {
    id: 1,
    type: "公益回访",
    title: "一间教室如何点亮孩子的第一堂美术课",
    author: "美芽集编辑部",
    read: "1.2k 阅读",
    cover: "https://picsum.photos/seed/story1/300/300",
  },
  {
    id: 2,
    type: "艺术家行动",
    title: "十位合作艺术家共同参与乡村美育共创计划",
    author: "项目组",
    read: "980 阅读",
    cover: "https://picsum.photos/seed/story2/300/300",
  },
]

export const events = [
  {
    id: 1,
    title: "艺术家面对面：春季联展分享会",
    type: "艺术沙龙",
    cover: "https://picsum.photos/seed/ev1/800/400",
    date: "2026-04-20 14:00",
    location: "美芽集艺术中心",
    participants: 86,
    price: 0,
    status: "报名中",
    tag: "公益免费",
    desc: "围绕本季合作艺术家作品展开导览与交流，现场开放提问与收藏咨询。",
  },
  {
    id: 2,
    title: "儿童水墨体验工作坊",
    type: "公益活动",
    cover: "https://picsum.photos/seed/ev2/800/400",
    date: "2026-04-25 10:00",
    location: "美芽集公益空间",
    participants: 45,
    price: 0,
    status: "报名中",
    tag: "亲子活动",
    desc: "面向亲子家庭开放的公益体验课，让孩子在轻松氛围中感受艺术表达。",
  },
]
