export const artists = [
  {
    id: 1,
    name: "范汇飞",
    bio: "北京当代写意油画研究院创作员，山东省美术家协会会员，时代青年油画社社员。作品多聚焦花卉与自然景观，以鲜活色彩和细腻笔触呈现四时生机。",
    avatar: "/artists-safe/fanhuifei/fanhuifei-001.jpg",
    location: "中国",
    followers: 1860,
    works: 18,
  },
  {
    id: 2,
    name: "郭争光",
    bio: "1980年生于龙岩，福建师范大学艺术硕士，福建幼儿师范高等专科学校美术教研室主任、副教授，中国美术家协会会员，擅长以民居与城镇景观书写在地记忆。",
    avatar: "/artists-safe/guozhengguang/guozhengguang-001.jpg",
    location: "福建龙岩",
    followers: 4280,
    works: 16,
  },
  {
    id: 3,
    name: "侯虹旭",
    bio: "上海美术家协会会员。2011年毕业于山东大学美术系获学士学位，2014年毕业于华东师范大学美术系获硕士学位，现工作生活于北京，创作关注都市语境与日常景观中的情感距离。",
    avatar: "/artists-safe/houhongxu/houhongxu-001.jpg",
    location: "北京",
    followers: 2960,
    works: 10,
  },
  {
    id: 4,
    name: "戢佳",
    bio: "笔名戢茹嘉，四川省美术家协会会员，长期深耕写意油画创作，作品多次入选全国性展览并获奖。",
    avatar: "/artists-safe/jijia/jijia-001.jpg",
    location: "四川成都",
    followers: 3920,
    works: 21,
  },
  {
    id: 5,
    name: "刘传珂",
    bio: "中国美术家协会会员，中国油画学会会员，北京当代中国写意油画研究院特约创作员，威海市美术家协会理事，吴冠中艺术馆特聘画家。2011年毕业于山东大学（威海）美术系，先后进修于王辉老师《和而不同》油画研修班及北京画院李江峰工作室。擅长以花卉与自然景致入画，画面兼具抒情气息与柔和色彩层次。",
    avatar: "/artists-safe/liuchuanke/liuchuanke-001.jpg",
    location: "山东威海",
    followers: 1740,
    works: 3,
  },
  {
    id: 6,
    name: "生辉",
    bio: "1978年生于山东东营，山东省美术家协会会员，山东省油画学会理事，北京当代中国写意油画院特约创作员，时代青年油画社社员。作品以写意油画语言表现山水与田野气象。",
    avatar: "/artists-safe/shenghui/shenghui-001.jpg",
    location: "山东东营",
    followers: 3650,
    works: 25,
  },
  {
    id: 7,
    name: "吴良孝",
    bio: "1977年生于福建省浦城县。2015年结业于清华大学美术学院当代艺术创作名家导师高级研修班，2016年结业于王辉油画工作室'和而不同'高研班。中国美术家协会会员，北京当代中国写意油画研究院学术委员会秘书、特约创作员，福建省油画学会会员，时代青年油画社社员。作品围绕山海、花意与静夜景象展开，以厚重笔触塑造情绪张力。",
    avatar: "/artists-safe/wuliangxiao/wuliangxiao-001.jpg",
    location: "福建浦城",
    followers: 2080,
    works: 8,
  },
  {
    id: 8,
    name: "吴有才",
    bio: "中国美术家协会会员，北京当代中国写意油画研究院特约创作员，海沧区美术家协会副主席，时代青年油画社社员。",
    avatar: "/artists-safe/wuyoucai/wuyoucai-001.jpg",
    location: "福建厦门",
    followers: 4460,
    works: 9,
  },
  {
    id: 9,
    name: "许丙屯",
    bio: "广东徐闻人。2022年获国家艺术基金青年创作资助，中国美术家协会会员，中国油画学会会员，北京当代中国写意油画研究院创作员，广东省美术家协会会员，广东水彩画研究会会员，李可染画院青年画院院聘艺术家，北方油画院理事，时代青年油画社成员。",
    avatar: "/artists-safe/xubingtun/xubingtun-001.jpg",
    location: "广东徐闻",
    followers: 5120,
    works: 11,
  },
  {
    id: 10,
    name: "张昆",
    bio: "中西表现绘画课题组成员，访问学者。山东省青年美术家协会会员，进修于中国传媒大学艺术创作院中西表现绘画高研班。擅长描绘山林、园林与田园意象，重视自然气息与诗意栖居的营造。",
    avatar: "/artists-safe/zhangkun/zhangkun-001.jpg",
    location: "中国",
    followers: 2310,
    works: 14,
  },
]

export const artworks = [
  {
    id: 1,
    title: "窗前的海棠花",
    aid: 1,
    artist: "范汇飞",
    price: 28000,
    orig: null,
    cat: "油画",
    style: "花卉写意",
    size: "50×60cm",
    year: "2025",
    mat: "布面油画",
    desc: "取景窗前盛放海棠，以温柔笔触描摹花影摇曳的春日气息。",
    img: "/artists-safe/fanhuifei/fanhuifei-002.jpg",
    views: 1320,
    sold: 0,
    stock: 1,
    featured: true,
    charityPct: 40,
  },
  {
    id: 2,
    title: "艾山烟雨",
    aid: 1,
    artist: "范汇飞",
    price: 36000,
    orig: null,
    cat: "油画",
    style: "风景写意",
    size: "60×80cm",
    year: "2025",
    mat: "布面油画",
    desc: "以湿润柔和的色层表现山岚氤氲，营造静谧而悠长的自然氛围。",
    img: "/artists-safe/fanhuifei/fanhuifei-003.jpg",
    views: 980,
    sold: 0,
    stock: 1,
    featured: false,
    charityPct: 40,
  },
  // ===== 范汇飞 · 补充作品 =====
  {
    id: 101,
    title: "又见韭花开",
    aid: 1,
    artist: "范汇飞",
    price: 26000,
    orig: null,
    cat: "油画",
    style: "花卉写意",
    size: "50×60cm",
    year: "2025",
    mat: "布面油画",
    desc: "韭菜花在画面中肆意绽放，以明快色彩传递生命力。",
    img: "/artists-safe/fanhuifei/fanhuifei-004.jpg",
    views: 720,
    sold: 0,
    stock: 1,
    featured: false,
    charityPct: 40,
  },
  {
    id: 102,
    title: "合花漫舞",
    aid: 1,
    artist: "范汇飞",
    price: 32000,
    orig: null,
    cat: "油画",
    style: "花卉写意",
    size: "60×80cm",
    year: "2025",
    mat: "布面油画",
    desc: "繁花交织如舞，色彩层叠中展现自然的丰饶。",
    img: "/artists-safe/fanhuifei/fanhuifei-005.jpg",
    views: 650,
    sold: 0,
    stock: 1,
    featured: false,
    charityPct: 40,
  },
  {
    id: 103,
    title: "荷韵",
    aid: 1,
    artist: "范汇飞",
    price: 32000,
    orig: null,
    cat: "油画",
    style: "花卉写意",
    size: "60×80cm",
    year: "2025",
    mat: "布面油画",
    desc: "以写意手法描绘荷花风姿，清雅而不失张力。",
    img: "/artists-safe/fanhuifei/fanhuifei-006.jpg",
    views: 780,
    sold: 0,
    stock: 1,
    featured: false,
    charityPct: 40,
  },
  {
    id: 104,
    title: "累累硕果",
    aid: 1,
    artist: "范汇飞",
    price: 34000,
    orig: null,
    cat: "油画",
    style: "静物花卉",
    size: "65×80cm",
    year: "2025",
    mat: "布面油画",
    desc: "饱满果实挂满枝头，以厚重肌理呈现丰收喜悦。",
    img: "/artists-safe/fanhuifei/fanhuifei-007.jpg",
    views: 690,
    sold: 0,
    stock: 1,
    featured: false,
    charityPct: 40,
  },
  {
    id: 105,
    title: "怒放",
    aid: 1,
    artist: "范汇飞",
    price: 26000,
    orig: null,
    cat: "油画",
    style: "花卉写意",
    size: "50×60cm",
    year: "2024",
    mat: "布面油画",
    desc: "花朵怒放姿态张扬，笔触奔放有力。",
    img: "/artists-safe/fanhuifei/fanhuifei-008.jpg",
    views: 710,
    sold: 0,
    stock: 1,
    featured: false,
    charityPct: 40,
  },
  {
    id: 106,
    title: "馨香",
    aid: 1,
    artist: "范汇飞",
    price: 30000,
    orig: null,
    cat: "油画",
    style: "花卉写意",
    size: "70×70cm",
    year: "2024",
    mat: "布面油画",
    desc: "方形构图中花香四溢，色调温暖含蓄。",
    img: "/artists-safe/fanhuifei/fanhuifei-009.jpg",
    views: 670,
    sold: 0,
    stock: 1,
    featured: false,
    charityPct: 40,
  },
  {
    id: 107,
    title: "芍药花开",
    aid: 1,
    artist: "范汇飞",
    price: 48000,
    orig: null,
    cat: "油画",
    style: "花卉写意",
    size: "120×120cm",
    year: "",
    mat: "布面油画",
    desc: "大幅方构图芍药盛开，气势恢宏。",
    img: "/artists-safe/fanhuifei/fanhuifei-010.jpg",
    views: 920,
    sold: 0,
    stock: 1,
    featured: false,
    charityPct: 40,
  },
  {
    id: 108,
    title: "石与花",
    aid: 1,
    artist: "范汇飞",
    price: 28000,
    orig: null,
    cat: "油画",
    style: "静物花卉",
    size: "60×70cm",
    year: "2025",
    mat: "布面油画",
    desc: "顽石与鲜花并置，刚柔相济的视觉对话。",
    img: "/artists-safe/fanhuifei/fanhuifei-011.jpg",
    views: 630,
    sold: 0,
    stock: 1,
    featured: false,
    charityPct: 40,
  },
  {
    id: 109,
    title: "蒲公英",
    aid: 1,
    artist: "范汇飞",
    price: 32000,
    orig: null,
    cat: "油画",
    style: "花卉写意",
    size: "60×80cm",
    year: "2025",
    mat: "布面油画",
    desc: "蒲公英随风飘散的轻盈瞬间，充满诗意。",
    img: "/artists-safe/fanhuifei/fanhuifei-012.jpg",
    views: 750,
    sold: 0,
    stock: 1,
    featured: false,
    charityPct: 40,
  },
  {
    id: 110,
    title: "通往海边的小路",
    aid: 1,
    artist: "范汇飞",
    price: 32000,
    orig: null,
    cat: "油画",
    style: "风景写意",
    size: "60×80cm",
    year: "2024",
    mat: "布面油画",
    desc: "蜿蜒小路引向远方海岸，引人遐思。",
    img: "/artists-safe/fanhuifei/fanhuifei-013.jpg",
    views: 680,
    sold: 0,
    stock: 1,
    featured: false,
    charityPct: 40,
  },
  {
    id: 111,
    title: "葳蕤山野",
    aid: 1,
    artist: "范汇飞",
    price: 42000,
    orig: null,
    cat: "油画",
    style: "风景写意",
    size: "60×120cm",
    year: "2018",
    mat: "布面油画",
    desc: "横幅构图中山林茂密，生机盎然。",
    img: "/artists-safe/fanhuifei/fanhuifei-014.jpg",
    views: 850,
    sold: 0,
    stock: 1,
    featured: false,
    charityPct: 40,
  },
  {
    id: 112,
    title: "无瑕",
    aid: 1,
    artist: "范汇飞",
    price: 26000,
    orig: null,
    cat: "油画",
    style: "花卉写意",
    size: "60×60cm",
    year: "2024",
    mat: "布面油画",
    desc: "纯净无瑕的花朵意象，简约而动人。",
    img: "/artists-safe/fanhuifei/fanhuifei-015.jpg",
    views: 600,
    sold: 0,
    stock: 1,
    featured: false,
    charityPct: 40,
  },
  {
    id: 113,
    title: "杏花次第开",
    aid: 1,
    artist: "范汇飞",
    price: 40000,
    orig: null,
    cat: "油画",
    style: "花卉写意",
    size: "100×100cm",
    year: "2025",
    mat: "布面油画",
    desc: "大面积杏花绽放，次第开放的热闹景象。",
    img: "/artists-safe/fanhuifei/fanhuifei-016.jpg",
    views: 890,
    sold: 0,
    stock: 1,
    featured: false,
    charityPct: 40,
  },
  {
    id: 114,
    title: "野花之一",
    aid: 1,
    artist: "范汇飞",
    price: 42000,
    orig: null,
    cat: "油画",
    style: "风景花卉",
    size: "60×120cm",
    year: "2025",
    mat: "布面油画",
    desc: "横幅展开的野花世界，自然生长的力量。",
    img: "/artists-safe/fanhuifei/fanhuifei-017.jpg",
    views: 770,
    sold: 0,
    stock: 1,
    featured: false,
    charityPct: 40,
  },
  {
    id: 115,
    title: "樱花絮语",
    aid: 1,
    artist: "范汇飞",
    price: 32000,
    orig: null,
    cat: "油画",
    style: "花卉写意",
    size: "60×80cm",
    year: "2025",
    mat: "布面油画",
    desc: "樱花飘落如絮语的浪漫意境。",
    img: "/artists-safe/fanhuifei/fanhuifei-018.jpg",
    views: 810,
    sold: 0,
    stock: 1,
    featured: false,
    charityPct: 40,
  },
  {
    id: 116,
    title: "绽放的花儿",
    aid: 1,
    artist: "范汇飞",
    price: 32000,
    orig: null,
    cat: "油画",
    style: "花卉写意",
    size: "60×80cm",
    year: "2024",
    mat: "布面油画",
    desc: "花朵尽情舒展的姿态，充满生命能量。",
    img: "/artists-safe/fanhuifei/fanhuifei-019.jpg",
    views: 730,
    sold: 0,
    stock: 1,
    featured: false,
    charityPct: 40,
  },
  {
    id: 117,
    title: "庄园的牡丹花",
    aid: 1,
    artist: "范汇飞",
    price: 26000,
    orig: null,
    cat: "油画",
    style: "花卉写意",
    size: "60×60cm",
    year: "2024",
    mat: "布面油画",
    desc: "庄园中的牡丹雍容华贵，典雅端庄。",
    img: "/artists-safe/fanhuifei/fanhuifei-020.jpg",
    views: 660,
    sold: 0,
    stock: 1,
    featured: false,
    charityPct: 40,
  },
  {
    id: 3,
    title: "湖畔春色",
    aid: 2,
    artist: "郭争光",
    price: 42000,
    orig: null,
    cat: "油画",
    style: "风景油画",
    size: "50×60cm",
    year: "2019",
    mat: "布面油画",
    desc: "湖畔与村舍在明亮色彩中层层铺开，传递春日生机与空间节奏。",
    img: "/artists-safe/guozhengguang/guozhengguang-002.jpg",
    views: 1560,
    sold: 0,
    stock: 1,
    featured: true,
    charityPct: 40,
  },
  {
    id: 4,
    title: "乐园",
    aid: 2,
    artist: "郭争光",
    price: 46000,
    orig: null,
    cat: "油画",
    style: "城市景观",
    size: "60×80cm",
    year: "2024",
    mat: "布面油画",
    desc: "将建筑与自然景色交织入画，形成既现实又带梦境感的空间记忆。",
    img: "/artists-safe/guozhengguang/guozhengguang-003.jpg",
    views: 1410,
    sold: 0,
    stock: 1,
    featured: false,
    charityPct: 40,
  },
  {
    id: 5,
    title: "石桥人家",
    aid: 2,
    artist: "郭争光",
    price: 39000,
    orig: null,
    cat: "油画",
    style: "人文风景",
    size: "40×80cm",
    year: "2023",
    mat: "布面油画",
    desc: "以石桥、民居与河岸构成画面主线，浓缩闽南生活气息。",
    img: "/artists-safe/guozhengguang/guozhengguang-004.jpg",
    views: 1210,
    sold: 0,
    stock: 1,
    featured: false,
    charityPct: 40,
  },
  // ===== 郭争光 · 补充作品 =====
  {
    id: 201,
    title: "百年鼓浪屿",
    aid: 2,
    artist: "郭争光",
    price: 52000,
    orig: null,
    cat: "油画",
    style: "城市景观",
    size: "50×110cm",
    year: "2015",
    mat: "布面油画",
    desc: "鼓浪屿历史建筑的百年风貌与时光沉淀。",
    img: "/artists-safe/guozhengguang/guozhengguang-005.jpg",
    views: 980,
    sold: 0,
    stock: 1,
    featured: false,
    charityPct: 40,
  },
  {
    id: 202,
    title: "鼓浪屿家园",
    aid: 2,
    artist: "郭争光",
    price: 50000,
    orig: null,
    cat: "油画",
    style: "人文风景",
    size: "100×100cm",
    year: "2020",
    mat: "布面油画",
    desc: "方形构图呈现鼓浪屿家园的温馨记忆。",
    img: "/artists-safe/guozhengguang/guozhengguang-006.jpg",
    views: 920,
    sold: 0,
    stock: 1,
    featured: false,
    charityPct: 40,
  },
  {
    id: 203,
    title: "鼓浪屿民居no17",
    aid: 2,
    artist: "郭争光",
    price: 48000,
    orig: null,
    cat: "油画",
    style: "建筑景观",
    size: "60×90cm",
    year: "2015",
    mat: "布面油画",
    desc: "鼓浪屿系列民居写生之一，捕捉在地生活痕迹。",
    img: "/artists-safe/guozhengguang/guozhengguang-007.jpg",
    views: 870,
    sold: 0,
    stock: 1,
    featured: false,
    charityPct: 40,
  },
  {
    id: 204,
    title: "鼓浪屿民居no4",
    aid: 2,
    artist: "郭争光",
    price: 62000,
    orig: null,
    cat: "油画",
    style: "建筑景观",
    size: "105×145cm",
    year: "2025",
    mat: "布面油画",
    desc: "大幅民居写生，细腻刻画鼓浪屿老建筑的神韵。",
    img: "/artists-safe/guozhengguang/guozhengguang-008.jpg",
    views: 1100,
    sold: 0,
    stock: 1,
    featured: false,
    charityPct: 40,
  },
  {
    id: 205,
    title: "贵州民居",
    aid: 2,
    artist: "郭争光",
    price: 42000,
    orig: null,
    cat: "油画",
    style: "人文风景",
    size: "50×100cm",
    year: "2023",
    mat: "布面油画",
    desc: "贵州山间民居的独特风貌与自然融合。",
    img: "/artists-safe/guozhengguang/guozhengguang-009.jpg",
    views: 780,
    sold: 0,
    stock: 1,
    featured: false,
    charityPct: 40,
  },
  {
    id: 206,
    title: "海港小镇",
    aid: 2,
    artist: "郭争光",
    price: 39000,
    orig: null,
    cat: "油画",
    style: "风景油画",
    size: "60×80cm",
    year: "2022",
    mat: "布面油画",
    desc: "海港小镇的日常景象，光影交织的港口生活。",
    img: "/artists-safe/guozhengguang/guozhengguang-010.jpg",
    views: 830,
    sold: 0,
    stock: 1,
    featured: false,
    charityPct: 40,
  },
  {
    id: 207,
    title: "宏村民居",
    aid: 2,
    artist: "郭争光",
    price: 42000,
    orig: null,
    cat: "油画",
    style: "人文风景",
    size: "50×100cm",
    year: "2024",
    mat: "布面油画",
    desc: "安徽宏村古村落的白墙黛瓦与水乡意境。",
    img: "/artists-safe/guozhengguang/guozhengguang-011.jpg",
    views: 860,
    sold: 0,
    stock: 1,
    featured: false,
    charityPct: 40,
  },
  {
    id: 208,
    title: "镜像",
    aid: 2,
    artist: "郭争光",
    price: 39000,
    orig: null,
    cat: "油画",
    style: "风景油画",
    size: "60×80cm",
    year: "2022",
    mat: "布面油画",
    desc: "镜像中的空间对话，虚实交叠的视觉趣味。",
    img: "/artists-safe/guozhengguang/guozhengguang-012.jpg",
    views: 740,
    sold: 0,
    stock: 1,
    featured: false,
    charityPct: 40,
  },
  {
    id: 209,
    title: "老巷新意",
    aid: 2,
    artist: "郭争光",
    price: 39000,
    orig: null,
    cat: "油画",
    style: "人文风景",
    size: "60×80cm",
    year: "2023",
    mat: "布面油画",
    desc: "古老巷弄中注入新的观察视角与色彩表达。",
    img: "/artists-safe/guozhengguang/guozhengguang-013.jpg",
    views: 800,
    sold: 0,
    stock: 1,
    featured: false,
    charityPct: 40,
  },
  {
    id: 210,
    title: "梦乐园",
    aid: 2,
    artist: "郭争光",
    price: 39000,
    orig: null,
    cat: "油画",
    style: "风景油画",
    size: "60×80cm",
    year: "2025",
    mat: "布面油画",
    desc: "如梦似幻的乐园场景，色彩明快而富有想象。",
    img: "/artists-safe/guozhengguang/guozhengguang-014.jpg",
    views: 890,
    sold: 0,
    stock: 1,
    featured: false,
    charityPct: 40,
  },
  {
    id: 211,
    title: "石门高古街",
    aid: 2,
    artist: "郭争光",
    price: 39000,
    orig: null,
    cat: "油画",
    style: "人文风景",
    size: "60×80cm",
    year: "2023",
    mat: "布面油画",
    desc: "古街巷的历史质感与现代绘画语言的结合。",
    img: "/artists-safe/guozhengguang/guozhengguang-015.jpg",
    views: 750,
    sold: 0,
    stock: 1,
    featured: false,
    charityPct: 40,
  },
  {
    id: 212,
    title: "田园秋色",
    aid: 2,
    artist: "郭争光",
    price: 39000,
    orig: null,
    cat: "油画",
    style: "风景油画",
    size: "60×80cm",
    year: "2024",
    mat: "布面油画",
    desc: "秋日田园的丰收色调，温暖宁静。",
    img: "/artists-safe/guozhengguang/guozhengguang-016.jpg",
    views: 820,
    sold: 0,
    stock: 1,
    featured: false,
    charityPct: 40,
  },
  {
    id: 213,
    title: "听海",
    aid: 2,
    artist: "郭争光",
    price: 36000,
    orig: null,
    cat: "油画",
    style: "海景写生",
    size: "60×80cm",
    year: "2017",
    mat: "布面油画",
    desc: "海边聆听涛声的静谧时刻。",
    img: "/artists-safe/guozhengguang/guozhengguang-017.jpg",
    views: 710,
    sold: 0,
    stock: 1,
    featured: false,
    charityPct: 40,
  },
  {
    id: 6,
    title: "远方",
    aid: 3,
    artist: "侯虹旭",
    price: 32000,
    orig: null,
    cat: "油画",
    style: "当代绘画",
    size: "50×70cm",
    year: "2021",
    mat: "布面油画",
    desc: "画面以人物与空间的若即若离，折射日常景观中的情绪距离。",
    img: "/artists-safe/houhongxu/houhongxu-002.jpg",
    views: 1280,
    sold: 0,
    stock: 1,
    featured: true,
    charityPct: 40,
  },
  {
    id: 7,
    title: "未来已来",
    aid: 3,
    artist: "侯虹旭",
    price: 34000,
    orig: null,
    cat: "油画",
    style: "当代绘画",
    size: "60×90cm",
    year: "2020",
    mat: "布面油画",
    desc: "以平静却带张力的构图，描绘现代生活中对未来的投射与想象。",
    img: "/artists-safe/houhongxu/houhongxu-003.jpg",
    views: 1190,
    sold: 0,
    stock: 1,
    featured: false,
    charityPct: 40,
  },
  // ===== 侯虹旭 · 补充作品 =====
  {
    id: 301,
    title: "猫的秘密2",
    aid: 3,
    artist: "侯虹旭",
    price: 30000,
    orig: null,
    cat: "油画",
    style: "当代绘画",
    size: "50×60cm",
    year: "2018",
    mat: "布面油画",
    desc: "猫与空间的微妙关系，日常中的神秘感。",
    img: "/artists-safe/houhongxu/houhongxu-004.jpg",
    views: 680,
    sold: 0,
    stock: 1,
    featured: false,
    charityPct: 40,
  },
  {
    id: 302,
    title: "幸福树",
    aid: 3,
    artist: "侯虹旭",
    price: 26000,
    orig: null,
    cat: "油画",
    style: "当代绘画",
    size: "40×55cm",
    year: "2020",
    mat: "布面油画",
    desc: "象征希望与生长的树形意象。",
    img: "/artists-safe/houhongxu/houhongxu-005.jpg",
    views: 620,
    sold: 0,
    stock: 1,
    featured: false,
    charityPct: 40,
  },
  {
    id: 303,
    title: "花花",
    aid: 3,
    artist: "侯虹旭",
    price: 28000,
    orig: null,
    cat: "油画",
    style: "当代绘画",
    size: "50×60cm",
    year: "2021",
    mat: "布面油画",
    desc: "花卉主题的当代表达，色彩柔和而富有情绪。",
    img: "/artists-safe/houhongxu/houhongxu-006.jpg",
    views: 650,
    sold: 0,
    stock: 1,
    featured: false,
    charityPct: 40,
  },
  {
    id: 304,
    title: "母与子1",
    aid: 3,
    artist: "侯虹旭",
    price: 22000,
    orig: null,
    cat: "油画",
    style: "人物绘画",
    size: "30×40cm",
    year: "2020",
    mat: "布面油画",
    desc: "母子题材的小幅温情刻画。",
    img: "/artists-safe/houhongxu/houhongxu-007.jpg",
    views: 580,
    sold: 0,
    stock: 1,
    featured: false,
    charityPct: 40,
  },
  {
    id: 305,
    title: "母与子3",
    aid: 3,
    artist: "侯虹旭",
    price: 32000,
    orig: null,
    cat: "油画",
    style: "人物绘画",
    size: "60×80cm",
    year: "2021",
    mat: "布面油画",
    desc: "母子系列大幅作品，情感表达更加饱满。",
    img: "/artists-safe/houhongxu/houhongxu-008.jpg",
    views: 720,
    sold: 0,
    stock: 1,
    featured: false,
    charityPct: 40,
  },
  {
    id: 306,
    title: "照见",
    aid: 3,
    artist: "侯虹旭",
    price: 28000,
    orig: null,
    cat: "油画",
    style: "当代绘画",
    size: "50×60cm",
    year: "2020",
    mat: "布面油画",
    desc: "自我观照的主题表达。",
    img: "/artists-safe/houhongxu/houhongxu-009.jpg",
    views: 600,
    sold: 0,
    stock: 1,
    featured: false,
    charityPct: 40,
  },
  {
    id: 307,
    title: "美丽的梦",
    aid: 3,
    artist: "侯虹旭",
    price: 28000,
    orig: null,
    cat: "油画",
    style: "当代绘画",
    size: "60cm圆",
    year: "2021",
    mat: "布面油画",
    desc: "圆形构图中的梦幻意象，温柔而含蓄。",
    img: "/artists-safe/houhongxu/houhongxu-010.jpg",
    views: 700,
    sold: 0,
    stock: 1,
    featured: false,
    charityPct: 40,
  },
  {
    id: 308,
    title: "母与子2",
    aid: 3,
    artist: "侯虹旭",
    price: 18000,
    orig: null,
    cat: "油画",
    style: "人物绘画",
    size: "24×30cm",
    year: "2020",
    mat: "布面油画",
    desc: "母子系列的精致小幅作品。",
    img: "/artists-safe/houhongxu/houhongxu-011.jpg",
    views: 520,
    sold: 0,
    stock: 1,
    featured: false,
    charityPct: 40,
  },
  {
    id: 8,
    title: "白石清风",
    aid: 4,
    artist: "戢佳",
    price: 38000,
    orig: null,
    cat: "油画",
    style: "写意油画",
    size: "60×60cm",
    year: "2025",
    mat: "布面油画",
    desc: "借清朗石景与流动光色，呈现写意油画中沉静而饱满的精神气质。",
    img: "/artists-safe/jijia/jijia-002.jpg",
    views: 1490,
    sold: 0,
    stock: 1,
    featured: true,
    charityPct: 40,
  },
  {
    id: 9,
    title: "借你一扇窗",
    aid: 4,
    artist: "戢佳",
    price: 46000,
    orig: null,
    cat: "油画",
    style: "写意油画",
    size: "120×100cm",
    year: "2023",
    mat: "布面油画",
    desc: "将窗景、光影与内在情绪并置，形成富有叙事感的观看体验。",
    img: "/artists-safe/jijia/jijia-003.jpg",
    views: 1350,
    sold: 0,
    stock: 1,
    featured: false,
    charityPct: 40,
  },
  {
    id: 10,
    title: "枣园秋熟",
    aid: 4,
    artist: "戢佳",
    price: 52000,
    orig: null,
    cat: "油画",
    style: "写意油画",
    size: "100×120cm",
    year: "2024",
    mat: "布面油画",
    desc: "以浓郁暖色捕捉秋日丰收景象，传递土地与季节的厚实力量。",
    img: "/artists-safe/jijia/jijia-004.jpg",
    views: 1180,
    sold: 0,
    stock: 1,
    featured: false,
    charityPct: 40,
  },
  // ===== 戢佳 · 补充作品 =====
  {
    id: 401,
    title: "青波",
    aid: 4,
    artist: "戢佳",
    price: 46000,
    orig: null,
    cat: "油画",
    style: "写意风景",
    size: "80×120cm",
    year: "2023",
    mat: "布面油画",
    desc: "青色波光中的自然韵律。",
    img: "/artists-safe/jijia/jijia-005.jpg",
    views: 950,
    sold: 0,
    stock: 1,
    featured: false,
    charityPct: 40,
  },
  {
    id: 402,
    title: "雕盘待客二",
    aid: 4,
    artist: "戢佳",
    price: 58000,
    orig: null,
    cat: "油画",
    style: "静物写生",
    size: "120×120cm",
    year: "2022",
    mat: "布面油画",
    desc: "大幅静物系列，以丰盛果盘呈现待客之意。",
    img: "/artists-safe/jijia/jijia-006.jpg",
    views: 1050,
    sold: 0,
    stock: 1,
    featured: false,
    charityPct: 40,
  },
  {
    id: 403,
    title: "雕盘待客之三",
    aid: 4,
    artist: "戢佳",
    price: 56000,
    orig: null,
    cat: "油画",
    style: "静物写生",
    size: "120×100cm",
    year: "2023",
    mat: "布面油画",
    desc: "雕盘系列之三，色彩层次丰富。",
    img: "/artists-safe/jijia/jijia-007.jpg",
    views: 980,
    sold: 0,
    stock: 1,
    featured: false,
    charityPct: 40,
  },
  {
    id: 404,
    title: "雕盘待客之四",
    aid: 4,
    artist: "戢佳",
    price: 56000,
    orig: null,
    cat: "油画",
    style: "静物写生",
    size: "120×100cm",
    year: "2023",
    mat: "布面油画",
    desc: "雕盘系列之四，构图饱满。",
    img: "/artists-safe/jijia/jijia-008.jpg",
    views: 920,
    sold: 0,
    stock: 1,
    featured: false,
    charityPct: 40,
  },
  {
    id: 405,
    title: "皓胶一树间",
    aid: 4,
    artist: "戢佳",
    price: 42000,
    orig: null,
    cat: "油画",
    style: "写意风景",
    size: "80×80cm",
    year: "2023",
    mat: "布面油画",
    desc: "方形构图中的树木意象，光影交错。",
    img: "/artists-safe/jijia/jijia-009.jpg",
    views: 870,
    sold: 0,
    stock: 1,
    featured: false,
    charityPct: 40,
  },
  {
    id: 406,
    title: "红调一号",
    aid: 4,
    artist: "戢佳",
    price: 42000,
    orig: null,
    cat: "油画",
    style: "抽象写意",
    size: "80×80cm",
    year: "2023",
    mat: "布面油画",
    desc: "红色基调的抽象表达，充满张力。",
    img: "/artists-safe/jijia/jijia-010.jpg",
    views: 790,
    sold: 0,
    stock: 1,
    featured: false,
    charityPct: 40,
  },
  {
    id: 407,
    title: "金色早春",
    aid: 4,
    artist: "戢佳",
    price: 42000,
    orig: null,
    cat: "油画",
    style: "写意风景",
    size: "80×80cm",
    year: "2023",
    mat: "布面油画",
    desc: "金色色调的春日意象，温暖明亮。",
    img: "/artists-safe/jijia/jijia-011.jpg",
    views: 850,
    sold: 0,
    stock: 1,
    featured: false,
    charityPct: 40,
  },
  {
    id: 408,
    title: "蓝溪坠霞",
    aid: 4,
    artist: "戢佳",
    price: 32000,
    orig: null,
    cat: "油画",
    style: "写意风景",
    size: "60×60cm",
    year: "2025",
    mat: "布面油画",
    desc: "蓝色溪流映照晚霞的诗意瞬间。",
    img: "/artists-safe/jijia/jijia-012.jpg",
    views: 720,
    sold: 0,
    stock: 1,
    featured: false,
    charityPct: 40,
  },
  {
    id: 409,
    title: "岭脚村",
    aid: 4,
    artist: "戢佳",
    price: 42000,
    orig: null,
    cat: "油画",
    style: "人文风景",
    size: "80×80cm",
    year: "2023",
    mat: "布面油画",
    desc: "乡村岭脚村的在地生活记录。",
    img: "/artists-safe/jijia/jijia-013.jpg",
    views: 800,
    sold: 0,
    stock: 1,
    featured: false,
    charityPct: 40,
  },
  {
    id: 410,
    title: "榴香华韵其一",
    aid: 4,
    artist: "戢佳",
    price: 58000,
    orig: null,
    cat: "油画",
    style: "花卉静物",
    size: "120×120cm",
    year: "2021",
    mat: "布面油画",
    desc: "大幅石榴主题静物，华丽而富有装饰感。",
    img: "/artists-safe/jijia/jijia-014.jpg",
    views: 1100,
    sold: 0,
    stock: 1,
    featured: false,
    charityPct: 40,
  },
  {
    id: 411,
    title: "日子",
    aid: 4,
    artist: "戢佳",
    price: 26000,
    orig: null,
    cat: "油画",
    style: "静物写生",
    size: "40×50cm",
    year: "2021",
    mat: "布面油画",
    desc: "日常生活中的小确幸。",
    img: "/artists-safe/jijia/jijia-015.jpg",
    views: 650,
    sold: 0,
    stock: 1,
    featured: false,
    charityPct: 40,
  },
  {
    id: 412,
    title: "日子二",
    aid: 4,
    artist: "戢佳",
    price: 26000,
    orig: null,
    cat: "油画",
    style: "静物写生",
    size: "40×50cm",
    year: "2021",
    mat: "布面油画",
    desc: "日子系列的延续，日常之美。",
    img: "/artists-safe/jijia/jijia-016.jpg",
    views: 600,
    sold: 0,
    stock: 1,
    featured: false,
    charityPct: 40,
  },
  {
    id: 413,
    title: "万里共葱郁",
    aid: 4,
    artist: "戢佳",
    price: 62000,
    orig: null,
    cat: "油画",
    style: "写意风景",
    size: "120×160cm",
    year: "2023",
    mat: "布面油画",
    desc: "大幅竖幅山水，绿意盎然。",
    img: "/artists-safe/jijia/jijia-017.jpg",
    views: 1150,
    sold: 0,
    stock: 1,
    featured: false,
    charityPct: 40,
  },
  {
    id: 414,
    title: "新颜·春雨润物",
    aid: 4,
    artist: "戢佳",
    price: 50000,
    orig: null,
    cat: "油画",
    style: "写意风景",
    size: "80×120cm",
    year: "2024",
    mat: "布面油画",
    desc: "春雨滋润万物的新生气息。",
    img: "/artists-safe/jijia/jijia-018.jpg",
    views: 930,
    sold: 0,
    stock: 1,
    featured: false,
    charityPct: 40,
  },
  {
    id: 415,
    title: "行行复行行",
    aid: 4,
    artist: "戢佳",
    price: 50000,
    orig: null,
    cat: "油画",
    style: "写意风景",
    size: "80×120cm",
    year: "2023",
    mat: "布面油画",
    desc: "旅途中的行进感与空间纵深。",
    img: "/artists-safe/jijia/jijia-019.jpg",
    views: 890,
    sold: 0,
    stock: 1,
    featured: false,
    charityPct: 40,
  },
  {
    id: 416,
    title: "意象李家山之一",
    aid: 4,
    artist: "戢佳",
    price: 58000,
    orig: null,
    cat: "油画",
    style: "人文风景",
    size: "100×150cm",
    year: "2025",
    mat: "布面油画",
    desc: "李家山古村落意象系列开篇之作。",
    img: "/artists-safe/jijia/jijia-020.jpg",
    views: 1080,
    sold: 0,
    stock: 1,
    featured: false,
    charityPct: 40,
  },
  {
    id: 417,
    title: "意象李家山之二",
    aid: 4,
    artist: "戢佳",
    price: 58000,
    orig: null,
    cat: "油画",
    style: "人文风景",
    size: "120×120cm",
    year: "2025",
    mat: "布面油画",
    desc: "李家山意象之二，方构图中的古村风貌。",
    img: "/artists-safe/jijia/jijia-021.jpg",
    views: 1020,
    sold: 0,
    stock: 1,
    featured: false,
    charityPct: 40,
  },
  {
    id: 418,
    title: "意象李家山之五",
    aid: 4,
    artist: "戢佳",
    price: 58000,
    orig: null,
    cat: "油画",
    style: "人文风景",
    size: "120×120cm",
    year: "2025",
    mat: "布面油画",
    desc: "李家山系列第五幅，深入村落细节。",
    img: "/artists-safe/jijia/jijia-022.jpg",
    views: 970,
    sold: 0,
    stock: 1,
    featured: false,
    charityPct: 40,
  },
  {
    id: 11,
    title: "读花观海",
    aid: 5,
    artist: "刘传珂",
    price: 26000,
    orig: null,
    cat: "油画",
    style: "花卉风景",
    size: "40×50cm",
    year: "2025",
    mat: "布面油画",
    desc: "花影与海意在一幅画中相互映照，色彩轻盈而富于诗意。",
    img: "/artists-safe/liuchuanke/liuchuanke-002.jpg",
    views: 860,
    sold: 0,
    stock: 1,
    featured: true,
    charityPct: 40,
  },
  {
    id: 12,
    title: "绽放",
    aid: 5,
    artist: "刘传珂",
    price: 22000,
    orig: null,
    cat: "油画",
    style: "花卉油画",
    size: "40×40cm",
    year: "2025",
    mat: "布面油画",
    desc: "以开放姿态的花朵为主体，笔触明快，画面充满春日生长感。",
    img: "/artists-safe/liuchuanke/liuchuanke-003.jpg",
    views: 740,
    sold: 0,
    stock: 1,
    featured: false,
    charityPct: 40,
  },
  // ===== 刘传珂 · 补充作品 =====
  {
    id: 501,
    title: "荷韵",
    aid: 5,
    artist: "刘传珂",
    price: 28000,
    orig: null,
    cat: "油画",
    style: "花卉风景",
    size: "50×80cm",
    year: "",
    mat: "布面油画",
    desc: "荷花与水面交相呼应，清雅脱俗的写意表达。",
    img: "/artists-safe/liuchuanke/liuchuanke-004.jpg",
    views: 680,
    sold: 0,
    stock: 1,
    featured: false,
    charityPct: 40,
  },
  {
    id: 13,
    title: "海边",
    aid: 6,
    artist: "生辉",
    price: 36000,
    orig: null,
    cat: "油画",
    style: "写意油画",
    size: "60×80cm",
    year: "2024",
    mat: "布面油画",
    desc: "以开放笔意描绘海边光线与空间起伏，展现自然景观的呼吸感。",
    img: "/artists-safe/shenghui/shenghui-002.jpg",
    views: 1440,
    sold: 0,
    stock: 1,
    featured: true,
    charityPct: 40,
  },
  {
    id: 14,
    title: "山水之梦之八",
    aid: 6,
    artist: "生辉",
    price: 24000,
    orig: null,
    cat: "丙烯油画",
    style: "写意风景",
    size: "50×40cm",
    year: "2025",
    mat: "布面丙烯油画",
    desc: "在梦幻般的山水构成中，探索自然与内心景象的交会。",
    img: "/artists-safe/shenghui/shenghui-003.jpg",
    views: 1120,
    sold: 0,
    stock: 1,
    featured: false,
    charityPct: 40,
  },
  {
    id: 15,
    title: "艺甸园的屋顶",
    aid: 6,
    artist: "生辉",
    price: 36000,
    orig: null,
    cat: "油画",
    style: "写意风景",
    size: "60×80cm",
    year: "2024",
    mat: "布面油画",
    desc: "将屋顶、天空与周边环境化作跳跃色块，形成明快节奏。",
    img: "/artists-safe/shenghui/shenghui-004.jpg",
    views: 960,
    sold: 0,
    stock: 1,
    featured: false,
    charityPct: 40,
  },
  // ===== 生辉 · 补充作品 =====
  {
    id: 601,
    title: "黑水洋的下午",
    aid: 6,
    artist: "生辉",
    price: 36000,
    orig: null,
    cat: "油画",
    style: "写意风景",
    size: "60×80cm",
    year: "2024",
    mat: "布面油画",
    desc: "午后海边的光影与色彩变化。",
    img: "/artists-safe/shenghui/shenghui-005.jpg",
    views: 820,
    sold: 0,
    stock: 1,
    featured: false,
    charityPct: 40,
  },
  {
    id: 602,
    title: "韭菜花",
    aid: 6,
    artist: "生辉",
    price: 48000,
    orig: null,
    cat: "油画",
    style: "花卉风景",
    size: "120×80cm",
    year: "2025",
    mat: "布面油画",
    desc: "大面积韭菜花田的壮阔景象。",
    img: "/artists-safe/shenghui/shenghui-006.jpg",
    views: 950,
    sold: 0,
    stock: 1,
    featured: false,
    charityPct: 40,
  },
  {
    id: 603,
    title: "练夫人祠",
    aid: 6,
    artist: "生辉",
    price: 36000,
    orig: null,
    cat: "油画",
    style: "人文风景",
    size: "60×80cm",
    year: "2024",
    mat: "布面油画",
    desc: "古建筑与人文记忆的结合。",
    img: "/artists-safe/shenghui/shenghui-007.jpg",
    views: 790,
    sold: 0,
    stock: 1,
    featured: false,
    charityPct: 40,
  },
  {
    id: 604,
    title: "山水之梦之一",
    aid: 6,
    artist: "生辉",
    price: 20000,
    orig: null,
    cat: "丙烯油画",
    style: "写意风景",
    size: "30×40cm",
    year: "2025",
    mat: "布面丙烯油画",
    desc: "山水梦境系列开篇。",
    img: "/artists-safe/shenghui/shenghui-008.jpg",
    views: 520,
    sold: 0,
    stock: 1,
    featured: false,
    charityPct: 40,
  },
  {
    id: 605,
    title: "山水之梦之二",
    aid: 6,
    artist: "生辉",
    price: 20000,
    orig: null,
    cat: "丙烯油画",
    style: "写意风景",
    size: "30×40cm",
    year: "2025",
    mat: "布面丙烯油画",
    desc: "山水梦境系列之二。",
    img: "/artists-safe/shenghui/shenghui-009.jpg",
    views: 500,
    sold: 0,
    stock: 1,
    featured: false,
    charityPct: 40,
  },
  {
    id: 606,
    title: "山水之梦之三",
    aid: 6,
    artist: "生辉",
    price: 20000,
    orig: null,
    cat: "丙烯油画",
    style: "写意风景",
    size: "30×40cm",
    year: "2025",
    mat: "布面丙烯油画",
    desc: "山水梦境系列之三。",
    img: "/artists-safe/shenghui/shenghui-019.jpg",
    views: 510,
    sold: 0,
    stock: 1,
    featured: false,
    charityPct: 40,
  },
  {
    id: 607,
    title: "山水之梦之四",
    aid: 6,
    artist: "生辉",
    price: 20000,
    orig: null,
    cat: "丙烯油画",
    style: "写意风景",
    size: "30×40cm",
    year: "2025",
    mat: "布面丙烯油画",
    desc: "山水梦境系列之四。",
    img: "/artists-safe/shenghui/shenghui-020.jpg",
    views: 490,
    sold: 0,
    stock: 1,
    featured: false,
    charityPct: 40,
  },
  {
    id: 608,
    title: "山水之梦之五",
    aid: 6,
    artist: "生辉",
    price: 20000,
    orig: null,
    cat: "丙烯油画",
    style: "写意风景",
    size: "30×40cm",
    year: "2025",
    mat: "布面丙烯油画",
    desc: "山水梦境系列之五。",
    img: "/artists-safe/shenghui/shenghui-021.jpg",
    views: 530,
    sold: 0,
    stock: 1,
    featured: false,
    charityPct: 40,
  },
  {
    id: 609,
    title: "山水之梦之六",
    aid: 6,
    artist: "生辉",
    price: 24000,
    orig: null,
    cat: "丙烯油画",
    style: "写意风景",
    size: "50×40cm",
    year: "2025",
    mat: "布面丙烯油画",
    desc: "山水梦境系列之六，幅面增大。",
    img: "/artists-safe/shenghui/shenghui-022.jpg",
    views: 600,
    sold: 0,
    stock: 1,
    featured: false,
    charityPct: 40,
  },
  {
    id: 610,
    title: "山水之梦之七",
    aid: 6,
    artist: "生辉",
    price: 24000,
    orig: null,
    cat: "丙烯油画",
    style: "写意风景",
    size: "50×40cm",
    year: "2025",
    mat: "布面丙烯油画",
    desc: "山水梦境系列之七。",
    img: "/artists-safe/shenghui/shenghui-010.jpg",
    views: 580,
    sold: 0,
    stock: 1,
    featured: false,
    charityPct: 40,
  },
  {
    id: 611,
    title: "山水之梦之九",
    aid: 6,
    artist: "生辉",
    price: 24000,
    orig: null,
    cat: "丙烯油画",
    style: "写意风景",
    size: "50×40cm",
    year: "2025",
    mat: "布面丙烯油画",
    desc: "山水梦境系列之九。",
    img: "/artists-safe/shenghui/shenghui-011.jpg",
    views: 570,
    sold: 0,
    stock: 1,
    featured: false,
    charityPct: 40,
  },
  {
    id: 612,
    title: "山水之梦之十",
    aid: 6,
    artist: "生辉",
    price: 24000,
    orig: null,
    cat: "丙烯油画",
    style: "写意风景",
    size: "50×40cm",
    year: "2025",
    mat: "布面丙烯油画",
    desc: "山水梦境系列之十。",
    img: "/artists-safe/shenghui/shenghui-012.jpg",
    views: 550,
    sold: 0,
    stock: 1,
    featured: false,
    charityPct: 40,
  },
  {
    id: 613,
    title: "山水之梦之十一",
    aid: 6,
    artist: "生辉",
    price: 24000,
    orig: null,
    cat: "丙烯油画",
    style: "写意风景",
    size: "50×40cm",
    year: "2025",
    mat: "布面丙烯油画",
    desc: "山水梦境系列之十一。",
    img: "/artists-safe/shenghui/shenghui-013.jpg",
    views: 540,
    sold: 0,
    stock: 1,
    featured: false,
    charityPct: 40,
  },
  {
    id: 614,
    title: "夏日田野之一",
    aid: 6,
    artist: "生辉",
    price: 36000,
    orig: null,
    cat: "丙烯油画",
    style: "田园风景",
    size: "60×80cm",
    year: "2023",
    mat: "布面丙烯油画",
    desc: "夏日田野的热烈气息。",
    img: "/artists-safe/shenghui/shenghui-014.jpg",
    views: 800,
    sold: 0,
    stock: 1,
    featured: false,
    charityPct: 40,
  },
  {
    id: 615,
    title: "夏日田野之二",
    aid: 6,
    artist: "生辉",
    price: 36000,
    orig: null,
    cat: "丙烯油画",
    style: "田园风景",
    size: "60×80cm",
    year: "2023",
    mat: "布面丙烯油画",
    desc: "夏日田野系列的延续。",
    img: "/artists-safe/shenghui/shenghui-015.jpg",
    views: 770,
    sold: 0,
    stock: 1,
    featured: false,
    charityPct: 40,
  },
  {
    id: 616,
    title: "正午之一",
    aid: 6,
    artist: "生辉",
    price: 36000,
    orig: null,
    cat: "丙烯油画",
    style: "田园风景",
    size: "60×80cm",
    year: "2023",
    mat: "布面丙烯油画",
    desc: "正午阳光下的强烈光影对比。",
    img: "/artists-safe/shenghui/shenghui-016.jpg",
    views: 750,
    sold: 0,
    stock: 1,
    featured: false,
    charityPct: 40,
  },
  {
    id: 617,
    title: "正午之二",
    aid: 6,
    artist: "生辉",
    price: 36000,
    orig: null,
    cat: "丙烯油画",
    style: "田园风景",
    size: "60×80cm",
    year: "2023",
    mat: "布面丙烯油画",
    desc: "正午系列第二幅。",
    img: "/artists-safe/shenghui/shenghui-023.jpg",
    views: 720,
    sold: 0,
    stock: 1,
    featured: false,
    charityPct: 40,
  },
  {
    id: 618,
    title: "郑魏村",
    aid: 6,
    artist: "生辉",
    price: 36000,
    orig: null,
    cat: "油画",
    style: "人文风景",
    size: "60×80cm",
    year: "2024",
    mat: "布面油画",
    desc: "郑魏村古村落的在地风貌。",
    img: "/artists-safe/shenghui/shenghui-017.jpg",
    views: 810,
    sold: 0,
    stock: 1,
    featured: false,
    charityPct: 40,
  },
  {
    id: 619,
    title: "远山",
    aid: 6,
    artist: "生辉",
    price: 50000,
    orig: null,
    cat: "油画",
    style: "写意风景",
    size: "120×80cm",
    year: "2025",
    mat: "布面油画",
    desc: "横幅远山意象，气势开阔。",
    img: "/artists-safe/shenghui/shenghui-018.jpg",
    views: 920,
    sold: 0,
    stock: 1,
    featured: false,
    charityPct: 40,
  },
  {
    id: 16,
    title: "惊涛",
    aid: 7,
    artist: "吴良孝",
    price: 32000,
    orig: null,
    cat: "油画",
    style: "海景表现",
    size: "60×80cm",
    year: "2025",
    mat: "布面油画",
    desc: "以翻涌海浪与厚重肌理构成强烈视觉张力，呈现山海之间的力量感。",
    img: "/artists-safe/wuliangxiao/wuliangxiao-002.jpg",
    views: 920,
    sold: 0,
    stock: 1,
    featured: true,
    charityPct: 40,
  },
  {
    id: 17,
    title: "秋意",
    aid: 7,
    artist: "吴良孝",
    price: 28000,
    orig: null,
    cat: "油画",
    style: "抒情风景",
    size: "60×80cm",
    year: "2025",
    mat: "布面油画",
    desc: "用沉静色层描绘秋日景致，在温润笔触中传达季节的内省气息。",
    img: "/artists-safe/wuliangxiao/wuliangxiao-003.jpg",
    views: 760,
    sold: 0,
    stock: 1,
    featured: false,
    charityPct: 40,
  },
  // ===== 吴良孝 · 补充作品 =====
  {
    id: 701,
    title: "惊涛之二",
    aid: 7,
    artist: "吴良孝",
    price: 32000,
    orig: null,
    cat: "油画",
    style: "海景表现",
    size: "60×80cm",
    year: "2025",
    mat: "布面油画",
    desc: "惊涛系列第二幅，海浪翻涌的延续表达。",
    img: "/artists-safe/wuliangxiao/wuliangxiao-004.jpg",
    views: 870,
    sold: 0,
    stock: 1,
    featured: false,
    charityPct: 40,
  },
  {
    id: 702,
    title: "居系列一",
    aid: 7,
    artist: "吴良孝",
    price: 38000,
    orig: null,
    cat: "油画",
    style: "人文风景",
    size: "80×80cm",
    year: "2024",
    mat: "布面油画",
    desc: "居系列开篇之作，关于居住与归属的思考。",
    img: "/artists-safe/wuliangxiao/wuliangxiao-005.jpg",
    views: 920,
    sold: 0,
    stock: 1,
    featured: false,
    charityPct: 40,
  },
  {
    id: 703,
    title: "夜",
    aid: 7,
    artist: "吴良孝",
    price: 28000,
    orig: null,
    cat: "油画",
    style: "抒情风景",
    size: "80×60cm",
    year: "2025",
    mat: "布面油画",
    desc: "夜色中的静谧与深沉。",
    img: "/artists-safe/wuliangxiao/wuliangxiao-006.jpg",
    views: 790,
    sold: 0,
    stock: 1,
    featured: false,
    charityPct: 40,
  },
  {
    id: 704,
    title: "灼灼其华之一",
    aid: 7,
    artist: "吴良孝",
    price: 38000,
    orig: null,
    cat: "油画",
    style: "花卉写意",
    size: "80×80cm",
    year: "2024",
    mat: "布面油画",
    desc: "灼灼其华花卉系列之一。",
    img: "/artists-safe/wuliangxiao/wuliangxiao-007.jpg",
    views: 900,
    sold: 0,
    stock: 1,
    featured: false,
    charityPct: 40,
  },
  {
    id: 705,
    title: "灼灼其华之二",
    aid: 7,
    artist: "吴良孝",
    price: 38000,
    orig: null,
    cat: "油画",
    style: "花卉写意",
    size: "80×80cm",
    year: "2024",
    mat: "布面油画",
    desc: "灼灼其华系列第二幅。",
    img: "/artists-safe/wuliangxiao/wuliangxiao-008.jpg",
    views: 880,
    sold: 0,
    stock: 1,
    featured: false,
    charityPct: 40,
  },
  // ===== 吴有才 · 修复 + 补充作品 =====
  {
    id: 18,
    title: "红色记忆之一",
    aid: 8,
    artist: "吴有才",
    price: 30000,
    orig: null,
    cat: "油画",
    style: "主题创作",
    size: "—",
    year: "2025",
    mat: "布面绘画",
    desc: "资料中收录的主题作品之一，以厚重色彩和叙事构图延续'红色记忆'系列表达。",
    img: "/artists-safe/wuyoucai/wuyoucai-002.jpg",
    views: 680,
    sold: 0,
    stock: 1,
    featured: false,
    charityPct: 40,
  },
  {
    id: 19,
    title: "红色记忆之二",
    aid: 8,
    artist: "吴有才",
    price: 30000,
    orig: null,
    cat: "油画",
    style: "主题创作",
    size: "—",
    year: "2025",
    mat: "布面绘画",
    desc: "延续人物与历史叙事表达，画面更强调群像氛围与精神力量。",
    img: "/artists-safe/wuyoucai/wuyoucai-005.png",
    views: 640,
    sold: 0,
    stock: 1,
    featured: false,
    charityPct: 40,
  },
  {
    id: 801,
    title: "苍翠",
    aid: 8,
    artist: "吴有才",
    price: 32000,
    orig: null,
    cat: "油画",
    style: "风景写生",
    size: "60×80cm",
    year: "2024",
    mat: "布面油画",
    desc: "郁郁葱葱的绿色山林景象。",
    img: "/artists-safe/wuyoucai/wuyoucai-006.png",
    views: 700,
    sold: 0,
    stock: 1,
    featured: false,
    charityPct: 40,
  },
  {
    id: 802,
    title: "汉风古韵",
    aid: 8,
    artist: "吴有才",
    price: 26000,
    orig: null,
    cat: "油画",
    style: "人文风景",
    size: "50×50cm",
    year: "2023",
    mat: "布面油画",
    desc: "汉代风格的古韵意象。",
    img: "/artists-safe/wuyoucai/wuyoucai-007.png",
    views: 590,
    sold: 0,
    stock: 1,
    featured: false,
    charityPct: 40,
  },
  {
    id: 803,
    title: "金溪古堡",
    aid: 8,
    artist: "吴有才",
    price: 42000,
    orig: null,
    cat: "油画",
    style: "人文风景",
    size: "60×120cm",
    year: "2023",
    mat: "布面油画",
    desc: "金溪古堡的历史风貌与人文气息。",
    img: "/artists-safe/wuyoucai/wuyoucai-008.png",
    views: 850,
    sold: 0,
    stock: 1,
    featured: false,
    charityPct: 40,
  },
  {
    id: 804,
    title: "九色鹿·信",
    aid: 8,
    artist: "吴有才",
    price: 48000,
    orig: null,
    cat: "油画",
    style: "主题创作",
    size: "100×100cm",
    year: "2020",
    mat: "布面绘画",
    desc: "九色鹿神话主题创作，寓意诚信与美好。",
    img: "/artists-safe/wuyoucai/wuyoucai-002.jpg",
    views: 1100,
    sold: 0,
    stock: 1,
    featured: false,
    charityPct: 40,
  },
  {
    id: 805,
    title: "秀山博物馆秋景",
    aid: 8,
    artist: "吴有才",
    price: 32000,
    orig: null,
    cat: "油画",
    style: "风景写生",
    size: "60×80cm",
    year: "2023",
    mat: "布面油画",
    desc: "秀山博物馆周边的秋季景色。",
    img: "/artists-safe/wuyoucai/wuyoucai-009.png",
    views: 730,
    sold: 0,
    stock: 1,
    featured: false,
    charityPct: 40,
  },
  {
    id: 806,
    title: "意象李家山",
    aid: 8,
    artist: "吴有才",
    price: 26000,
    orig: null,
    cat: "油画",
    style: "人文风景",
    size: "50×50cm",
    year: "2024",
    mat: "布面油画",
    desc: "李家山古村落的意象表达之一。",
    img: "/artists-safe/wuyoucai/wuyoucai-003.jpg",
    views: 650,
    sold: 0,
    stock: 1,
    featured: false,
    charityPct: 40,
  },
  {
    id: 807,
    title: "意象李家山2",
    aid: 8,
    artist: "吴有才",
    price: 26000,
    orig: null,
    cat: "油画",
    style: "人文风景",
    size: "50×50cm",
    year: "2024",
    mat: "布面油画",
    desc: "李家山意象系列第二幅。",
    img: "/artists-safe/wuyoucai/wuyoucai-004.jpg",
    views: 620,
    sold: 0,
    stock: 1,
    featured: false,
    charityPct: 40,
  },
  {
    id: 20,
    title: "秋日",
    aid: 9,
    artist: "许丙屯",
    price: 30000,
    orig: null,
    cat: "油画",
    style: "风景油画",
    size: "50×50cm",
    year: "2024",
    mat: "布面油画",
    desc: "用沉稳而明亮的色调表现秋景层次，画面饱含南方自然气息。",
    img: "/artists-safe/xubingtun/xubingtun-002.jpg",
    views: 1380,
    sold: 0,
    stock: 1,
    featured: true,
    charityPct: 40,
  },
  // ===== 许丙屯 · 补充作品 =====
  {
    id: 901,
    title: "冬韵",
    aid: 9,
    artist: "许丙屯",
    price: 30000,
    orig: null,
    cat: "油画",
    style: "风景油画",
    size: "50×50cm",
    year: "2024",
    mat: "布面油画",
    desc: "冬日静谧中的冷调之美。",
    img: "/artists-safe/xubingtun/xubingtun-003.jpg",
    views: 720,
    sold: 0,
    stock: 1,
    featured: false,
    charityPct: 40,
  },
  {
    id: 902,
    title: "古城",
    aid: 9,
    artist: "许丙屯",
    price: 30000,
    orig: null,
    cat: "油画",
    style: "风景油画",
    size: "50×50cm",
    year: "2024",
    mat: "布面油画",
    desc: "古城墙与历史痕迹的当代表达。",
    img: "/artists-safe/xubingtun/xubingtun-004.jpg",
    views: 680,
    sold: 0,
    stock: 1,
    featured: false,
    charityPct: 40,
  },
  {
    id: 903,
    title: "古树",
    aid: 9,
    artist: "许丙屯",
    price: 30000,
    orig: null,
    cat: "油画",
    style: "风景油画",
    size: "50×50cm",
    year: "2024",
    mat: "布面油画",
    desc: "古老树木的坚韧生命力。",
    img: "/artists-safe/xubingtun/xubingtun-005.jpg",
    views: 640,
    sold: 0,
    stock: 1,
    featured: false,
    charityPct: 40,
  },
  {
    id: 904,
    title: "海浪",
    aid: 9,
    artist: "许丙屯",
    price: 30000,
    orig: null,
    cat: "油画",
    style: "风景油画",
    size: "50×50cm",
    year: "2024",
    mat: "布面油画",
    desc: "海浪翻涌的力量感。",
    img: "/artists-safe/xubingtun/xubingtun-006.jpg",
    views: 710,
    sold: 0,
    stock: 1,
    featured: false,
    charityPct: 40,
  },
  {
    id: 905,
    title: "江南",
    aid: 9,
    artist: "许丙屯",
    price: 30000,
    orig: null,
    cat: "油画",
    style: "风景油画",
    size: "50×50cm",
    year: "2024",
    mat: "布面油画",
    desc: "江南水乡的温婉意境。",
    img: "/artists-safe/xubingtun/xubingtun-007.jpg",
    views: 760,
    sold: 0,
    stock: 1,
    featured: false,
    charityPct: 40,
  },
  {
    id: 906,
    title: "绿芭蕉",
    aid: 9,
    artist: "许丙屯",
    price: 30000,
    orig: null,
    cat: "油画",
    style: "风景花卉",
    size: "50×50cm",
    year: "2024",
    mat: "布面油画",
    desc: "芭蕉叶的翠绿生机。",
    img: "/artists-safe/xubingtun/xubingtun-008.jpg",
    views: 670,
    sold: 0,
    stock: 1,
    featured: false,
    charityPct: 40,
  },
  {
    id: 907,
    title: "夏日",
    aid: 9,
    artist: "许丙屯",
    price: 30000,
    orig: null,
    cat: "油画",
    style: "风景油画",
    size: "50×50cm",
    year: "2024",
    mat: "布面油画",
    desc: "夏日阳光下的明亮色调。",
    img: "/artists-safe/xubingtun/xubingtun-009.jpg",
    views: 700,
    sold: 0,
    stock: 1,
    featured: false,
    charityPct: 40,
  },
  {
    id: 908,
    title: "渔港",
    aid: 9,
    artist: "许丙屯",
    price: 30000,
    orig: null,
    cat: "油画",
    style: "风景油画",
    size: "50×50cm",
    year: "2024",
    mat: "布面油画",
    desc: "渔港码头的日常景象。",
    img: "/artists-safe/xubingtun/xubingtun-010.jpg",
    views: 650,
    sold: 0,
    stock: 1,
    featured: false,
    charityPct: 40,
  },
  {
    id: 909,
    title: "早秋",
    aid: 9,
    artist: "许丙屯",
    price: 30000,
    orig: null,
    cat: "油画",
    style: "风景油画",
    size: "50×50cm",
    year: "2024",
    mat: "布面油画",
    desc: "初秋时节的微妙色彩变化。",
    img: "/artists-safe/xubingtun/xubingtun-011.jpg",
    views: 730,
    sold: 0,
    stock: 1,
    featured: false,
    charityPct: 40,
  },
  {
    id: 910,
    title: "秋荷",
    aid: 9,
    artist: "许丙屯",
    price: 30000,
    orig: null,
    cat: "油画",
    style: "风景油画",
    size: "50×50cm",
    year: "2024",
    mat: "布面油画",
    desc: "以简洁构成与温润色层表现荷塘秋意，安静中见力量。",
    img: "/artists-safe/xubingtun/xubingtun-012.jpg",
    views: 920,
    sold: 0,
    stock: 1,
    featured: false,
    charityPct: 40,
  },
  // ===== 张昆 · 补充 + 修复ID =====
  {
    id: 1001,
    title: "园林一角",
    aid: 10,
    artist: "张昆",
    price: 26000,
    orig: null,
    cat: "油画",
    style: "风景油画",
    size: "40×40cm",
    year: "2025",
    mat: "布面油画",
    desc: "取园林一隅入画，在细腻层次中传达静观自然的闲适意境。",
    img: "/artists-safe/zhangkun/zhangkun-002.jpg",
    views: 870,
    sold: 0,
    stock: 1,
    featured: true,
    charityPct: 40,
  },
  {
    id: 1002,
    title: "香韵",
    aid: 10,
    artist: "张昆",
    price: 32000,
    orig: null,
    cat: "油画",
    style: "风景油画",
    size: "60×80cm",
    year: "2025",
    mat: "布面油画",
    desc: "花木与空间在柔和色彩中展开，营造温润而富有诗性的氛围。",
    img: "/artists-safe/zhangkun/zhangkun-003.jpg",
    views: 790,
    sold: 0,
    stock: 1,
    featured: false,
    charityPct: 40,
  },
  {
    id: 1003,
    title: "田园锦绣",
    aid: 10,
    artist: "张昆",
    price: 34000,
    orig: null,
    cat: "油画",
    style: "田园风景",
    size: "60×80cm",
    year: "2025",
    mat: "布面油画",
    desc: "以饱满色彩表现田园景观的明媚与丰盛，富有生活温度。",
    img: "/artists-safe/zhangkun/zhangkun-004.jpg",
    views: 830,
    sold: 0,
    stock: 1,
    featured: false,
    charityPct: 40,
  },
  {
    id: 1004,
    title: "迎日圣山",
    aid: 10,
    artist: "张昆",
    price: 36000,
    orig: null,
    cat: "油画",
    style: "山水风景",
    size: "60×80cm",
    year: "",
    mat: "布面油画",
    desc: "圣山迎日的庄严意象。",
    img: "/artists-safe/zhangkun/zhangkun-005.jpg",
    views: 860,
    sold: 0,
    stock: 1,
    featured: false,
    charityPct: 40,
  },
  {
    id: 1005,
    title: "半坡秋林",
    aid: 10,
    artist: "张昆",
    price: 36000,
    orig: null,
    cat: "油画",
    style: "风景油画",
    size: "60×80cm",
    year: "",
    mat: "布面油画",
    desc: "半山坡上秋林的层次变化。",
    img: "/artists-safe/zhangkun/zhangkun-006.jpg",
    views: 800,
    sold: 0,
    stock: 1,
    featured: false,
    charityPct: 40,
  },
  {
    id: 1006,
    title: "丛林叠翠",
    aid: 10,
    artist: "张昆",
    price: 36000,
    orig: null,
    cat: "油画",
    style: "风景油画",
    size: "60×80cm",
    year: "",
    mat: "布面油画",
    desc: "茂密丛林中层层叠叠的绿色。",
    img: "/artists-safe/zhangkun/zhangkun-007.jpg",
    views: 820,
    sold: 0,
    stock: 1,
    featured: false,
    charityPct: 40,
  },
  {
    id: 1007,
    title: "秘山野居",
    aid: 10,
    artist: "张昆",
    price: 42000,
    orig: null,
    cat: "油画",
    style: "田园风景",
    size: "70×90cm",
    year: "",
    mat: "布面油画",
    desc: "深山野居的隐逸意境。",
    img: "/artists-safe/zhangkun/zhangkun-008.jpg",
    views: 920,
    sold: 0,
    stock: 1,
    featured: false,
    charityPct: 40,
  },
  {
    id: 1008,
    title: "暖冬",
    aid: 10,
    artist: "张昆",
    price: 36000,
    orig: null,
    cat: "油画",
    style: "风景油画",
    size: "60×80cm",
    year: "",
    mat: "布面油画",
    desc: "冬日里温暖的色彩与光影。",
    img: "/artists-safe/zhangkun/zhangkun-009.jpg",
    views: 780,
    sold: 0,
    stock: 1,
    featured: false,
    charityPct: 40,
  },
  {
    id: 1009,
    title: "瓶影揽春",
    aid: 10,
    artist: "张昆",
    price: 32000,
    orig: null,
    cat: "油画",
    style: "静物花卉",
    size: "60×80cm",
    year: "",
    mat: "布面油画",
    desc: "瓶中花影揽住春光。",
    img: "/artists-safe/zhangkun/zhangkun-010.jpg",
    views: 750,
    sold: 0,
    stock: 1,
    featured: false,
    charityPct: 40,
  },
  {
    id: 1010,
    title: "山间日照",
    aid: 10,
    artist: "张昆",
    price: 36000,
    orig: null,
    cat: "油画",
    style: "风景油画",
    size: "60×80cm",
    year: "",
    mat: "布面油画",
    desc: "山间阳光洒落的温暖瞬间。",
    img: "/artists-safe/zhangkun/zhangkun-011.jpg",
    views: 810,
    sold: 0,
    stock: 1,
    featured: false,
    charityPct: 40,
  },
  {
    id: 1011,
    title: "盛夏",
    aid: 10,
    artist: "张昆",
    price: 24000,
    orig: null,
    cat: "油画",
    style: "风景油画",
    size: "40×50cm",
    year: "",
    mat: "布面油画",
    desc: "盛夏时节的热烈气息。",
    img: "/artists-safe/zhangkun/zhangkun-012.jpg",
    views: 620,
    sold: 0,
    stock: 1,
    featured: false,
    charityPct: 40,
  },
  {
    id: 1012,
    title: "泰山秋色",
    aid: 10,
    artist: "张昆",
    price: 38000,
    orig: null,
    cat: "油画",
    style: "山水风景",
    size: "60×80cm",
    year: "",
    mat: "布面油画",
    desc: "泰山秋季的山色层次。",
    img: "/artists-safe/zhangkun/zhangkun-013.jpg",
    views: 900,
    sold: 0,
    stock: 1,
    featured: false,
    charityPct: 40,
  },
  {
    id: 1013,
    title: "泰山松",
    aid: 10,
    artist: "张昆",
    price: 38000,
    orig: null,
    cat: "油画",
    style: "山水风景",
    size: "60×80cm",
    year: "",
    mat: "布面油画",
    desc: "泰山松树的苍劲姿态。",
    img: "/artists-safe/zhangkun/zhangkun-014.jpg",
    views: 880,
    sold: 0,
    stock: 1,
    featured: false,
    charityPct: 40,
  },
  {
    id: 1014,
    title: "又一村",
    aid: 10,
    artist: "张昆",
    price: 36000,
    orig: null,
    cat: "油画",
    style: "田园风景",
    size: "60×80cm",
    year: "",
    mat: "布面油画",
    desc: "柳暗花明又一村的意境表达。",
    img: "/artists-safe/zhangkun/zhangkun-015.jpg",
    views: 840,
    sold: 0,
    stock: 1,
    featured: false,
    charityPct: 40,
  },
]

export const categories = ["全部", "国画", "油画", "水彩", "雕塑", "摄影", "陶艺"]

export const categoryIcons = {
  全部: "🌟",
  国画: "🎋",
  油画: "🖼️",
  水彩: "🌈",
  雕塑: "🗿",
  摄影: "📷",
  陶艺: "🏺",
}

export const exhibitions = [
  {
    id: 1,
    title: "春季名家精品展",
    type: "线上展览",
    cover: "https://picsum.photos/seed/ex1/800/500",
    artist: "美芽集合作艺术家",
    location: "线上展厅",
    date: "2026-04-20 至 2026-05-20",
    price: 0,
    status: "正在展出",
    tag: "免费参观",
    desc: "汇聚十位合作艺术家的最新代表作，呈现花卉、风景与写意油画等多元面貌。",
    highlights: ["线上观展", "十位艺术家联展", "代表作品集中呈现"],
  },
  {
    id: 2,
    title: "美育公益联展",
    type: "公益展览",
    cover: "https://picsum.photos/seed/ex2/800/500",
    artist: "美芽集公益计划",
    location: "美芽集公益空间",
    date: "2026-05-01 至 2026-06-01",
    price: 0,
    status: "即将开始",
    tag: "公益主题",
    desc: "围绕公益美育与乡村振兴主题，展示艺术家参与公益项目的创作力量。",
    highlights: ["公益主题策展", "乡村美育内容呈现", "艺术共创交流"],
  },
]

export const orders = [
  {
    id: "MYJ20260408001",
    status: "待发货",
    date: "2026-04-08 14:20",
    total: 64000,
    arts: [
      {
        title: "窗前的海棠花",
        artist: "范汇飞",
        price: 28000,
        img: "/artists-safe/fanhuifei/fanhuifei-002.jpg",
      },
      {
        title: "乐园",
        artist: "郭争光",
        price: 46000,
        img: "/artists-safe/guozhengguang/guozhengguang-003.jpg",
      },
    ],
  },
  {
    id: "MYJ20260402002",
    status: "运输中",
    date: "2026-04-02 09:15",
    total: 38000,
    arts: [
      {
        title: "白石清风",
        artist: "戢佳",
        price: 38000,
        img: "/artists-safe/jijia/jijia-002.jpg",
      },
    ],
  },
  {
    id: "MYJ20260326003",
    status: "已完成",
    date: "2026-03-26 16:48",
    total: 30000,
    arts: [
      {
        title: "秋日",
        artist: "许丙屯",
        price: 30000,
        img: "/artists-safe/xubingtun/xubingtun-002.jpg",
      },
    ],
  },
]

export const charity = [
  {
    id: 1,
    title: "乡村美育教室计划",
    tag: "长期项目",
    cover: "/charity-articles/yongtai.jpg",
    desc: "联合艺术家与志愿者，为乡村学校建设可持续运转的美育教室与课程体系。",
    raised: 128000,
    beneficiaries: 180,
  },
  {
    id: 2,
    title: "儿童写生活动支持计划",
    tag: "公益活动",
    cover: "https://picsum.photos/seed/charity2/800/500",
    desc: "为偏远地区儿童提供写生工具包、课程支持与线下艺术体验活动。",
    raised: 86000,
    beneficiaries: 96,
  },
]

export const charityActivities = [
  {
    id: 1,
    title: "2024年新萌芽户外公益讲堂第一课——美在永泰",
    tag: "户外公益讲堂",
    date: "2024-05-02",
    location: "福建永泰",
    participants: 60,
    cover: "/charity-articles/yongtai.jpg",
    desc: "以户外讲堂为起点，把艺术体验与乡村自然课堂结合，让孩子们在真实景观中感受色彩、观察与表达。",
  },
  {
    id: 2,
    title: "爱与美的播种：艺术家以美育赋能乡村振兴——美在婺源公益讲堂活动",
    tag: "公益讲堂",
    date: "2023-03-21",
    location: "江西婺源",
    participants: 88,
    cover: "/charity-articles/wuyuan.jpg",
    desc: "新萌芽专项基金联合艺术家走进婺源，以公益讲堂和现场交流把美育带入乡村振兴的日常场景。",
  },
  {
    id: 3,
    title: "美在洽湾——《侨爱心365-乡村美育》户外公益讲堂",
    tag: "乡村美育",
    date: "2023-11-24",
    location: "福建洽湾",
    participants: 72,
    cover: "/charity-articles/qiawan.jpg",
    desc: "围绕《侨爱心365-乡村美育》主题开展户外公益讲堂，让孩子们在开放课堂里接触绘画与审美启蒙。",
  },
  {
    id: 4,
    title: "美在青州——2025年《侨爱心365-乡村美育》户外公益讲堂",
    tag: "年度公益课",
    date: "2025-10-14",
    location: "山东青州",
    participants: 95,
    cover: "/charity-articles/qingzhou.jpg",
    desc: "2025年度公益讲堂落地青州，延续乡村美育实践，通过艺术互动与观察训练提升孩子们的创造力。",
  },
  {
    id: 5,
    title: "美在榕江——美育浸润乡村学校课堂，艺术赋能乡村文化振兴",
    tag: "课堂浸润",
    date: "2023-08-25",
    location: "贵州榕江",
    participants: 84,
    cover: "/charity-articles/rongjiang.jpg",
    desc: "把美育课堂真正带进乡村学校，让艺术教育从一次活动延伸为更长期、更深入的文化陪伴。",
  },
  {
    id: 6,
    title: "美在文山——2025年《侨爱心365-乡村美育》户外公益讲堂",
    tag: "户外公益讲堂",
    date: "2025-04-24",
    location: "云南文山",
    participants: 90,
    cover: "/charity-articles/wenshan-lecture.jpg",
    desc: "以文山在地文化与自然环境为背景，组织艺术家开展户外公益讲堂，增强孩子们的观察与创作兴趣。",
  },
  {
    id: 7,
    title: "美在文山——时代青年油画社公益写生教学系列活动（第六回）圆满结束",
    tag: "写生教学",
    date: "2025-04-21",
    location: "云南文山",
    participants: 68,
    cover: "/charity-articles/wenshan-workshop.jpg",
    desc: "聚焦公益写生教学与现场实践，通过连续课程与互动示范，让乡村孩子获得更具体的绘画体验。",
  },
]

export const stories = [
  {
    id: 1,
    type: "公益回访",
    title: "一间教室如何点亮孩子的第一堂美术课",
    author: "美芽集编辑部",
    read: "1.2k 阅读",
    cover: "https://picsum.photos/seed/story1/300/300",
  },
  {
    id: 2,
    type: "艺术家行动",
    title: "十位合作艺术家共同参与乡村美育共创计划",
    author: "项目组",
    read: "980 阅读",
    cover: "https://picsum.photos/seed/story2/300/300",
  },
]

export const charityArticleDetails = {
  1: {
    title: "2024年新萌芽户外公益讲堂第一课——美在永泰",
    date: "2024年05月02日",
    author: "新萌芽TREE",
    location: "福建永泰",
    tag: "户外公益讲堂",
    cover: "/charity-articles/yongtai.jpg",
    sections: [
      "4月22号，时代青年油画社与中国华侨公益基金会新萌芽专项基金在福建省福州市永泰二中共同开展了2024年首次乡村美育户外公益讲堂活动，活动包括捐赠画材、走访困难学生、写生课堂、师生共绘一幅画、与乡村教师交流业务等。",
      "本次活动共向学校捐赠了46类、1753套（件）画材，总价值六万余元。善款皆是通过去年的活动零零散散向七、八十位新萌芽支持者募集到的，涓涓细流汇成江河，有大家的支持我们才完成了这次活动。",
      "美育是乡村人才振兴的重要路径之一，可以赋能广大乡村学校培养德智体美劳全面发展的优秀人才。2023年时代青年油画社在河北、江西、贵州等地开展公益教学活动的同时，作为艺术团队也主动承担着社会责任，我们通过试点的方式探索出多路径的乡村帮扶办法，形成一系列乡村美育活动，本次福州永泰之行便是2024年的首次美育实践。",
      "参加此次活动的艺术家有：王春华、许丙屯、郭争光、戢佳、吴有才、江哲、陈康康，在活动正式开始前3天就已经到达永泰二中，提前和学校相关部门沟通，准备课程，运输物资，筹备会场等准备工作。活动过程中在校园内开展户外写生、校内墙绘特色课程，在互动交流和公益支教课上，艺术家们手把手教师生们写字与绘画，面对面讲授绘画的原理，用画笔从不同角度展现家乡的美，引导学生们充分发挥想象力、观察力与创造力，共同完成了长30米，高5米的墙绘。墙绘结束后，孩子们告诉我们，他们这两天过得太开心了，希望以后能多些户外写生的机会。",
      "学校课程结束之后，时代青年油画社的艺术家们又和当地老师交流工作，探讨绘画教学的问题。并开展了座谈会，就欠发达地区的美育教学问题进行探讨，两位当地教师对当前面临的困境和需要的资源支持提出了建议。",
      "中国华侨公益基金会及福州县部门相关领导也应邀参加此次活动，并共同走访慰问了两名困难学生，送去书籍等学习用品。",
      "孤举者难起，众行者易趋。今后我们时代青年油画社的艺术家们将汇聚更多力量，推动社会公益事业的发展，愿更多的人来加入我们，一起用艺术助力乡村美育，用爱心托起未来梦想！",
    ],
    images: [
      "/charity-articles/images/article1_1.png",
      "/charity-articles/images/article1_2.png",
      "/charity-articles/images/article1_3.png",
      "/charity-articles/images/article1_4.png",
      "/charity-articles/images/article1_5.png",
    ],
  },
  2: {
    title: "爱与美的播种——美在婺源公益讲堂活动",
    date: "2023年03月21日",
    author: "时代青年油画社",
    location: "江西婺源",
    tag: "公益讲堂",
    cover: "/charity-articles/wuyuan.jpg",
    sections: [
      "阳春三月，中国华侨公益基金会新萌芽专项基金联合时代青年油画社走进江西婺源，开展《美在婺源》公益讲堂活动。艺术家们以美育为纽带，将艺术的种子播撒在这片充满诗意的土地上。",
      "本次活动以《爱与美的播种》为主题，通过公益讲座、现场示范、互动体验等形式，让乡村孩子近距离感受艺术的魅力。画家们在婺源的徽派建筑与油菜花海间开展写生创作，同时为当地师生带来生动的美术课堂。",
      "参与活动的艺术家们纷纷表示，能够用自己的专业所长为乡村美育贡献力量，是一件非常有意义的事情。艺术不分地域，每个孩子都应该拥有接触美、发现美、创造美的机会。",
      "活动中还向当地学校捐赠了一批优质画材和学习用品，希望能够为学校的日常美术教学提供实实在在的支持。我们相信，持续的美育投入终将开花结果。",
    ],
    images: [
      "/charity-articles/images/article2_1.jpg",
      "/charity-articles/images/article2_2.jpg",
      "/charity-articles/images/article2_3.jpg",
      "/charity-articles/images/article2_4.jpg",
      "/charity-articles/images/article2_5.jpg",
      "/charity-articles/images/article2_6.jpg",
      "/charity-articles/images/article2_7.jpg",
      "/charity-articles/images/article2_8.jpg",
      "/charity-articles/images/article2_9.jpg",
      "/charity-articles/images/article2_10.jpg",
      "/charity-articles/images/article2_11.jpg",
      "/charity-articles/images/article2_12.jpg",
      "/charity-articles/images/article2_13.jpg",
    ],
  },
  3: {
    title: "美在洽湾——《侨爱心365-乡村美育》户外公益讲堂",
    date: "2023年11月24日",
    author: "时代青年油画社",
    location: "江西南丰洽湾",
    tag: "乡村美育",
    cover: "/charity-articles/qiawan.jpg",
    sections: [
      "江西南丰历史悠久，素有千年古邑、飞城走塔、耕读传家的美名，更是唐宋八大家曾巩的故里。",
      "2023年11月15日，中国华侨公益基金会新萌芽专项基金联合时代青年油画社在江西省抚州市南丰县洽湾镇举办第五期乡村美育公益活动——《侨爱心365·美在洽湾》。油画社的艺术家为洽湾小学70名学生开展了公益美育课堂，并为全校173名学生捐赠了画材物资。",
      "参加这次活动的艺术家有：吴良孝、陈康康、王春华、许丙屯、戢茹嘉、刘传珂、郭争光、吴有才、生辉、陈燕仁。",
      "在活动前期，新萌芽专项基金和时代青年油画社的代表们与洽湾镇中心小学的校长进行了座谈，并对学校的情况进行了深入了解：学校在校生共有173人，一半以上的学生是留守儿童，师资配备方面艺术类教师极其匮乏，目前全校是由一名语文老师代艺术课程。",
      "画家们经过在镇上考察与交流后多次开会讨论，最终确定好了上课方案和物资准备。",
      "次日，艺术家团队首先带领学生们在户外写生。写生前几位画家分别就建筑特征及周边环境给大家做了讲解，引导孩子们用画笔尽情表达自己的所思所想。学生们积极认真，敢于创作，对户外写生充满了极高的热情。",
      "随后开展的特色课程环节中，艺术家们通过示范和一对一指导，让孩子们体验了从观察到落笔的完整过程。看到孩子们专注的眼神和完成作品后的笑容，所有付出的努力都变得值得。",
    ],
    images: [
      "/charity-articles/images/article3_1.jpg",
      "/charity-articles/images/article3_2.png",
      "/charity-articles/images/article3_3.png",
      "/charity-articles/images/article3_4.jpg",
      "/charity-articles/images/article3_5.jpg",
      "/charity-articles/images/article3_6.jpg",
      "/charity-articles/images/article3_7.jpg",
      "/charity-articles/images/article3_8.jpg",
      "/charity-articles/images/article3_9.png",
      "/charity-articles/images/article3_10.jpg",
      "/charity-articles/images/article3_11.jpg",
      "/charity-articles/images/article3_12.jpg",
      "/charity-articles/images/article3_13.png",
      "/charity-articles/images/article3_14.jpg",
      "/charity-articles/images/article3_15.jpg",
    ],
  },
  4: {
    title: "美在青州——2025年《侨爱心365-乡村美育》户外公益讲堂",
    date: "2025年10月14日",
    author: "时代青年油画社",
    location: "山东青州",
    tag: "年度公益课",
    cover: "/charity-articles/qingzhou.jpg",
    sections: [
      "2025年10月11日，由中国华侨公益基金会、山东省侨联主办，中国华侨公益基金会新萌芽专项基金、时代青年油画社承办，青州市侨联、青州市云门山回民学校、青州美术馆、青州市油画学会协办的《美在青州—2025年侨爱心365-乡村美育户外公益讲堂》艺术活动在云门山回民学校举办。",
      "本次活动以《美在青州》为主题，通过画材捐赠、户外写生课堂、学生走访、师生共绘一幅画、写生示范、座谈交流等形式，为当地师生带去丰富的美育体验，助力乡村美育发展，以艺术为媒介传递爱心，充分发挥美育在乡村教育中的滋养作用。",
      "出席本次活动的嘉宾有：中国华侨公益基金会新萌芽专项基金理事姜灿，青州市教育教学研究院院长杨玉昌，新萌芽专项基金项目主任陈康，以及青州市相关部门负责同志。",
      "参加本次活动的画家有：中国美术家协会会员吴良孝；中国美术家协会会员吴有才；中国美术家协会会员陈淑敏；北京当代写意油画研究院创作员范汇飞；山东省美术家协会会员生辉；以及青州市油画学会的公益志愿者们。",
      "10月11日上午，中国华侨公益基金会新萌芽专项基金向青州市云门山回民学校捐赠了各类画材，为乡村美育提供硬件支持。",
      "10月12日上午，时代青年油画社画家在青州古城与学校美术教师及当地油画学会同道们开展写生交流活动，相互分享创作心得和理念。",
      "10月12日下午，画家们在青州油画院同学校美术教师及当地油画学会同道们开展了《美在青州》交流座谈会，共同讨论如何提升美育教学质量。",
      "我们希望通过持续的美育行动，让乡村孩子也能享有优质的艺术教育。未来，我们将继续深化民族美育深耕计划，推动城乡美育资源联动，让艺术的种子在更多乡村生根发芽。",
    ],
    images: [
      "/charity-articles/images/article4_1.png",
      "/charity-articles/images/article4_2.png",
      "/charity-articles/images/article4_3.jpg",
      "/charity-articles/images/article4_4.png",
      "/charity-articles/images/article4_5.jpg",
      "/charity-articles/images/article4_6.jpg",
      "/charity-articles/images/article4_7.jpg",
      "/charity-articles/images/article4_8.png",
      "/charity-articles/images/article4_9.png",
      "/charity-articles/images/article4_10.jpg",
      "/charity-articles/images/article4_11.jpg",
      "/charity-articles/images/article4_12.jpg",
      "/charity-articles/images/article4_13.jpg",
      "/charity-articles/images/article4_14.jpg",
      "/charity-articles/images/article4_15.jpg",
    ],
  },
  5: {
    title: "美在榕江——美育浸润乡村学校课堂，艺术赋能乡村文化振兴",
    date: "2023年08月25日",
    author: "时代青年油画社",
    location: "贵州榕江",
    tag: "课堂浸润",
    cover: "/charity-articles/rongjiang.jpg",
    sections: [
      "贵州省黔东南苗族侗族自治州榕江县，这片被群山环抱的土地上，有一群热爱艺术的乡村孩子。他们渴望着专业的美术指导，期待着用画笔描绘家乡的山山水水。",
      "2023年8月，时代青年油画社携手中国华侨公益基金会新萌芽专项基金走进榕江，把美育课堂真正带进乡村学校。这不是一次性的展示活动，而是希望将艺术教育的火种留在当地，让美育从一次活动延伸为更长期、更深入的文化陪伴。",
      "活动期间，艺术家们深入榕江的多所乡村学校，了解当地美育教学的实际困境。面对师资匮乏、器材不足的现状，大家更加坚定了持续帮扶的决心。",
      "通过现场授课、作品点评、创作指导等多种形式，艺术家们让乡村孩子体验到完整的艺术学习过程。许多孩子是第一次有机会接受专业画家的面对面指导，眼中满是好奇与欣喜。",
      "除了课堂教学，活动还包括向学校捐赠美术用品、与当地教师座谈交流等内容。我们希望通过授人以渔的方式，帮助提升本地教师的美术教学能力，留下带不走的美术教育资源。",
    ],
    images: [
      "/charity-articles/images/article5_1.jpg",
      "/charity-articles/images/article5_2.jpg",
      "/charity-articles/images/article5_3.jpg",
      "/charity-articles/images/article5_4.jpg",
      "/charity-articles/images/article5_5.jpg",
      "/charity-articles/images/article5_6.jpg",
      "/charity-articles/images/article5_7.jpg",
      "/charity-articles/images/article5_8.jpg",
      "/charity-articles/images/article5_9.jpg",
      "/charity-articles/images/article5_10.jpg",
      "/charity-articles/images/article5_11.jpg",
    ],
  },
  6: {
    title: "美在文山——2025年《侨爱心365-乡村美育》户外公益讲堂",
    date: "2025年04月24日",
    author: "时代青年油画社",
    location: "云南文山",
    tag: "户外公益讲堂",
    cover: "/charity-articles/wenshan-lecture.jpg",
    sections: [
      "云南文山，这片位于祖国西南边陲的美丽土地，以其独特的喀斯特地貌和多民族文化而闻名。2025年4月，时代青年油画社再次出发，在这里开启了新一年的乡村美育实践。",
      "由中国华侨公益基金会新萌芽专项基金主办的《美在文山—2025年侨爱心365-乡村美育户外公益讲堂》，以文山在地文化与自然环境为背景，组织艺术家开展户外公益讲堂，增强孩子们的观察与创作兴趣。",
      "活动选址于文山的乡村学校，这里的孩子大多来自少数民族家庭，有着与生俱来的色彩感和对美的朴素感知。艺术家们因势利导，将当地的民族元素融入教学内容，让孩子们用熟悉的视角去重新审视身边的世界。",
      "课堂上，画家们带领学生走出教室，在真实的自然景观中进行观察和写生。从构图到配色，从光影到笔触，每一个知识点都结合眼前的具体景物来讲解，让抽象的艺术概念变得可感可知。",
      "除了写生训练，活动还安排了师生共绘长卷的集体创作环节。巨大的画布铺展在操场上，孩子们与艺术家并肩执笔，共同描绘心中的美丽家园。这种协作式的艺术体验，不仅锻炼了绘画技能，更培养了团队精神和集体荣誉感。",
      "活动最后，所有参与的学生都收到了专属的画具礼包，希望这份礼物能够陪伴他们在艺术的道路上继续前行。",
    ],
    images: [
      "/charity-articles/images/article6_1.jpg",
      "/charity-articles/images/article6_2.jpg",
      "/charity-articles/images/article6_3.jpg",
      "/charity-articles/images/article6_4.jpg",
      "/charity-articles/images/article6_5.jpg",
      "/charity-articles/images/article6_6.jpg",
      "/charity-articles/images/article6_7.jpg",
      "/charity-articles/images/article6_8.jpg",
      "/charity-articles/images/article6_9.jpg",
      "/charity-articles/images/article6_10.jpg",
      "/charity-articles/images/article6_11.jpg",
      "/charity-articles/images/article6_12.jpg",
      "/charity-articles/images/article6_13.jpg",
      "/charity-articles/images/article6_14.jpg",
      "/charity-articles/images/article6_15.jpg",
    ],
  },
  7: {
    title: "美在文山——时代青年油画社公益写生教学系列活动（第六回）圆满结束",
    date: "2025年04月21日",
    author: "时代青年油画社",
    location: "云南文山",
    tag: "写生教学",
    cover: "/charity-articles/wenshan-workshop.jpg",
    sections: [
      "继户外公益讲堂之后，时代青年油画社在云南文山继续推进公益写生教学系列活动第六回。这是一次聚焦深度教学与实践的创作型公益活动，旨在让乡村孩子获得更系统、更具体的绘画体验。",
      "与前期的普及性美育活动不同，写生教学系列更强调技法的传授和创作的引导。参与活动的学生在之前的公益讲堂中已展现出浓厚的兴趣和对艺术的敏感度，本次活动为他们提供了进一步深造的机会。",
      "活动内容涵盖风景写生、静物组合、人物速写等多个板块。每位艺术家负责一个小组，进行小班化的精细指导。从取景构图到调色技法，从线条运用到画面处理，孩子们在反复练习中逐步掌握了基本要领。",
      "值得一提的是，本次活动中有多位学生完成了人生中的第一幅完整写生作品。当这些稚嫩却真诚的作品被展示出来时，在场的所有人都深受感动。艺术的价值不仅在于技巧的高度，更在于表达的真诚。",
      "活动尾声举办了小型作品汇报展，学生们的画作被精心装裱后陈列展出。当地学校领导和家长们受邀参观，看着孩子们的作品，许多人眼眶湿润。这些画作不仅是学习的成果，更是乡村孩子自信心的见证。",
      "时代青年油画社表示，写生教学系列活动将持续举办，希望通过年复一年的坚持，在更多乡村孩子心中种下艺术的种子，静待花开的那一天。",
    ],
    images: [
      "/charity-articles/images/article7_1.jpg",
      "/charity-articles/images/article7_2.jpg",
      "/charity-articles/images/article7_3.jpg",
      "/charity-articles/images/article7_4.jpg",
      "/charity-articles/images/article7_5.jpg",
      "/charity-articles/images/article7_6.jpg",
      "/charity-articles/images/article7_7.webp",
      "/charity-articles/images/article7_8.jpg",
      "/charity-articles/images/article7_9.jpg",
      "/charity-articles/images/article7_10.jpg",
      "/charity-articles/images/article7_11.webp",
      "/charity-articles/images/article7_12.jpg",
      "/charity-articles/images/article7_13.jpg",
      "/charity-articles/images/article7_14.jpg",
      "/charity-articles/images/article7_15.png",
    ],
  },
}

export const charityProjectDetails = {
  1: {
    title: "乡村美育教室计划：把一间教室做成长期发生的美育现场",
    date: "2026年04月20日",
    author: "美芽集公益项目组",
    location: "福建永泰及合作乡村学校",
    tag: "长期项目",
    cover: "/charity-articles/yongtai.jpg",
    sections: [
      "“乡村美育教室计划”并不是一次性的到访活动，而是围绕乡村学校真实需求建立的长期项目。我们希望通过空间改造、课程支持、画材补给与志愿者协作，把原本零散发生的公益课堂，慢慢沉淀成一间能够持续运转的美育教室，让孩子们在自己的校园里拥有稳定接触艺术的机会。",
      "项目启动前，我们会先和学校管理者及一线教师进行深入沟通，了解学校原有的美术课程情况、空间使用条件、学生年龄结构以及最紧迫的教学困难。很多乡村学校并不缺少孩子的好奇心，真正缺的是一间可被反复使用的教室、足够支撑课堂开展的基础画材，以及能把审美教育真正带进日常教学的课程方法。",
      "因此，这个计划的第一步并不是“举办一场好看的活动”，而是先搭建一个能长期服务学校的底层框架。我们会根据学校条件补充基础画架、颜料、纸张、陈列板和收纳系统，同时整理适合乡村学校实施的课程包，让老师和志愿者即使在艺术资源有限的情况下，也能够把课程持续开下去。",
      "在具体教学上，项目强调“从身边出发”的观察方式。孩子们不一定要先认识遥远的美术馆，他们可以先从校舍、田野、山路、树影和家乡的日常器物开始，用画笔记录自己最熟悉的生活环境。这样的课程设计，既降低了理解门槛，也能让乡村儿童在表达中重新发现自己生活世界的价值与美感。",
      "艺术家与志愿者的加入，则让这间教室拥有了更鲜活的公共性。合作艺术家会以驻点工作坊、示范写生、共创墙绘和作品点评等形式参与教学；志愿者则协助整理材料、维护课程秩序、记录学生作品，并持续跟进教室使用情况。我们希望美育教室不仅是一间上课的房间，也是一处让孩子敢于表达、愿意展示、乐于合作的小型公共文化空间。",
      "项目推进过程中，我们尤其重视“留给学校什么”。除了现场课程与物资支持，我们也会把活动中形成的范例作品、展示方式和课程反馈整理归档，帮助学校建立自己的教室使用手册与学生作品记录。这样即使艺术家离开，教室仍然能够继续被老师使用，被学生记住，被一届又一届新的孩子重新激活。",
      "对于美芽集来说，这个计划的意义并不只在于帮助多少人完成一堂课，而在于尝试建立一种更耐心的公益方法。我们相信，美育真正产生影响，往往不是因为某次活动足够热闹，而是因为孩子们在很长一段时间里，都能反复进入同一间教室，反复拿起画笔，反复确认自己的感受值得被看见。乡村美育教室计划，想做的正是这样一件缓慢却重要的事。",
    ],
    images: [
      "/charity-articles/images/article1_1.png",
      "/charity-articles/images/article1_2.png",
      "/charity-articles/images/article1_3.png",
      "/charity-articles/images/article1_4.png",
      "/charity-articles/images/article1_5.png",
      "/charity-articles/images/article3_4.jpg",
      "/charity-articles/images/article3_5.jpg",
      "/charity-articles/images/article5_4.jpg",
      "/charity-articles/images/article6_4.jpg",
    ],
  },
}

export const events = [
  {
    id: 1,
    title: "艺术家面对面：春季联展分享会",
    type: "艺术沙龙",
    cover: "https://picsum.photos/seed/ev1/800/400",
    date: "2026-04-20 14:00",
    location: "美芽集艺术中心",
    participants: 86,
    price: 0,
    status: "报名中",
    tag: "公益免费",
    desc: "围绕本季合作艺术家作品展开导览与交流，现场开放提问与收藏咨询。",
  },
  {
    id: 2,
    title: "儿童水墨体验工作坊",
    type: "公益活动",
    cover: "https://picsum.photos/seed/ev2/800/400",
    date: "2026-04-25 10:00",
    location: "美芽集公益空间",
    participants: 45,
    price: 0,
    status: "报名中",
    tag: "亲子活动",
    desc: "面向亲子家庭开放的公益体验课，让孩子在轻松氛围中感受艺术表达。",
  },
]
