export const artists = [
  {
    id: 1,
    name: "范汇飞",
    bio: "青年油画艺术家，作品多聚焦花卉与自然景观，以鲜活色彩和细腻笔触呈现四时生机。",
    avatar: "/artists/fanhuifei/范汇飞《窗前的海棠花》50x60cm 2025年.jpg",
    location: "中国",
    followers: 1860,
    works: 19,
  },
  {
    id: 2,
    name: "郭争光",
    bio: "1980年生于龙岩，福建师范大学艺术硕士，福建幼儿师范高等专科学校美术教研室主任、副教授，中国美术家协会会员，擅长以民居与城镇景观书写在地记忆。",
    avatar: "/artists/guozhengguang/郭争光生活照.jpg",
    location: "福建龙岩",
    followers: 4280,
    works: 17,
  },
  {
    id: 3,
    name: "侯虹旭",
    bio: "上海美术家协会会员，毕业于山东大学与华东师范大学美术系，现工作生活于北京，创作关注都市语境与日常景观中的情感距离。",
    avatar: "/artists/houhongxu/侯虹旭《远方》 50×70cm 布面油画 2021年.jpg",
    location: "北京",
    followers: 2960,
    works: 10,
  },
  {
    id: 4,
    name: "戢佳",
    bio: "笔名戢茹嘉，四川省美术家协会会员，长期深耕写意油画创作，作品多次入选全国性展览并获奖。",
    avatar: "/artists/jijia/一、戢佳《白石清风》60x60cm 布面油画 2025年.jpg",
    location: "四川成都",
    followers: 3920,
    works: 21,
  },
  {
    id: 5,
    name: "刘传珂",
    bio: "油画艺术家，擅长以花卉与自然景致入画，画面兼具抒情气息与柔和色彩层次。",
    avatar: "/artists/liuchuanke/刘传珂《读花观海》40×50cm 布面油画.jpg",
    location: "中国",
    followers: 1740,
    works: 3,
  },
  {
    id: 6,
    name: "生辉",
    bio: "1978年生于山东东营，山东省美术家协会会员、山东省油画学会理事，北京当代中国写意油画院特约创作员，作品以写意油画语言表现山水与田野气象。",
    avatar: "/artists/shenghui/生辉工作照.jpg",
    location: "山东东营",
    followers: 3650,
    works: 25,
  },
  {
    id: 7,
    name: "吴良孝",
    bio: "油画艺术家，作品围绕山海、花意与静夜景象展开，以厚重笔触和浓烈色彩塑造情绪张力。",
    avatar: "/artists/wuliangxiao/4177a9f54de70f330c44a6b5939afc42.jpg",
    location: "中国",
    followers: 2080,
    works: 2,
  },
  {
    id: 8,
    name: "吴有才",
    bio: "中国美术家协会会员，北京当代中国写意油画研究院特约创作员，海沧区美术家协会副主席，近年持续以“红色记忆”系列与风景作品活跃于全国展览。",
    avatar: "/artists/wuyoucai/一.png",
    location: "福建厦门",
    followers: 4460,
    works: 2,
  },
  {
    id: 9,
    name: "许丙屯",
    bio: "广东徐闻人，中国美术家协会会员、中国油画学会会员，曾获国家艺术基金青年创作资助，作品多次入选全国重要展览并在公益拍卖中获得广泛关注。",
    avatar: "/artists/xubingtun/一、许丙屯《秋日》50×50cm 布面油画 2024年.JPG",
    location: "广东徐闻",
    followers: 5120,
    works: 11,
  },
  {
    id: 10,
    name: "张昆",
    bio: "风景题材艺术家，擅长描绘山林、园林与田园意象，画面色彩丰沛，重视自然气息与诗意栖居的营造。",
    avatar: "/artists/zhangkun/一、园林一角40×40.jpg",
    location: "中国",
    followers: 2310,
    works: 14,
  },
]

export const artworks = [
  {
    id: 1,
    title: "窗前的海棠花",
    aid: 1,
    artist: "范汇飞",
    price: 28000,
    orig: null,
    cat: "油画",
    style: "花卉写意",
    size: "50×60cm",
    year: "2025",
    mat: "布面油画",
    desc: "取景窗前盛放海棠，以温柔笔触描摹花影摇曳的春日气息。",
    img: "/artists/fanhuifei/范汇飞《窗前的海棠花》50x60cm 2025年.jpg",
    views: 1320,
    sold: 0,
    stock: 1,
    featured: true,
    charityPct: 40,
  },
  {
    id: 2,
    title: "艾山烟雨",
    aid: 1,
    artist: "范汇飞",
    price: 36000,
    orig: null,
    cat: "油画",
    style: "风景写意",
    size: "60×80cm",
    year: "2025",
    mat: "布面油画",
    desc: "以湿润柔和的色层表现山岚氤氲，营造静谧而悠长的自然氛围。",
    img: "/artists/fanhuifei/范汇飞《艾山烟雨》60x80cm 2025年.jpg",
    views: 980,
    sold: 0,
    stock: 1,
    featured: false,
    charityPct: 40,
  },
  {
    id: 3,
    title: "湖畔春色",
    aid: 2,
    artist: "郭争光",
    price: 42000,
    orig: null,
    cat: "油画",
    style: "风景油画",
    size: "50×60cm",
    year: "2019",
    mat: "布面油画",
    desc: "湖畔与村舍在明亮色彩中层层铺开，传递春日生机与空间节奏。",
    img: "/artists/guozhengguang/一、郭争光《湖畔春色》50×60cm  布面油画  2019年.jpg",
    views: 1560,
    sold: 0,
    stock: 1,
    featured: true,
    charityPct: 40,
  },
  {
    id: 4,
    title: "乐园",
    aid: 2,
    artist: "郭争光",
    price: 46000,
    orig: null,
    cat: "油画",
    style: "城市景观",
    size: "60×80cm",
    year: "2024",
    mat: "布面油画",
    desc: "将建筑与自然景色交织入画，形成既现实又带梦境感的空间记忆。",
    img: "/artists/guozhengguang/二、郭争光《乐园》60×80cm   布面油画  2024年.jpg",
    views: 1410,
    sold: 0,
    stock: 1,
    featured: false,
    charityPct: 40,
  },
  {
    id: 5,
    title: "石桥人家",
    aid: 2,
    artist: "郭争光",
    price: 39000,
    orig: null,
    cat: "油画",
    style: "人文风景",
    size: "40×80cm",
    year: "2023",
    mat: "布面油画",
    desc: "以石桥、民居与河岸构成画面主线，浓缩闽南生活气息。",
    img: "/artists/guozhengguang/三、郭争光《石桥人家》40×80cm  布面油画  2023年.jpg",
    views: 1210,
    sold: 0,
    stock: 1,
    featured: false,
    charityPct: 40,
  },
  {
    id: 6,
    title: "远方",
    aid: 3,
    artist: "侯虹旭",
    price: 32000,
    orig: null,
    cat: "油画",
    style: "当代绘画",
    size: "50×70cm",
    year: "2021",
    mat: "布面油画",
    desc: "画面以人物与空间的若即若离，折射日常景观中的情绪距离。",
    img: "/artists/houhongxu/侯虹旭《远方》 50×70cm 布面油画 2021年.jpg",
    views: 1280,
    sold: 0,
    stock: 1,
    featured: true,
    charityPct: 40,
  },
  {
    id: 7,
    title: "未来已来",
    aid: 3,
    artist: "侯虹旭",
    price: 34000,
    orig: null,
    cat: "油画",
    style: "当代绘画",
    size: "60×90cm",
    year: "2020",
    mat: "布面油画",
    desc: "以平静却带张力的构图，描绘现代生活中对未来的投射与想象。",
    img: "/artists/houhongxu/侯虹旭《未来已来》60×90cm 布面油画 2020年.jpg",
    views: 1190,
    sold: 0,
    stock: 1,
    featured: false,
    charityPct: 40,
  },
  {
    id: 8,
    title: "白石清风",
    aid: 4,
    artist: "戢佳",
    price: 38000,
    orig: null,
    cat: "油画",
    style: "写意油画",
    size: "60×60cm",
    year: "2025",
    mat: "布面油画",
    desc: "借清朗石景与流动光色，呈现写意油画中沉静而饱满的精神气质。",
    img: "/artists/jijia/一、戢佳《白石清风》60x60cm 布面油画 2025年.jpg",
    views: 1490,
    sold: 0,
    stock: 1,
    featured: true,
    charityPct: 40,
  },
  {
    id: 9,
    title: "借你一扇窗",
    aid: 4,
    artist: "戢佳",
    price: 46000,
    orig: null,
    cat: "油画",
    style: "写意油画",
    size: "120×100cm",
    year: "2023",
    mat: "布面油画",
    desc: "将窗景、光影与内在情绪并置，形成富有叙事感的观看体验。",
    img: "/artists/jijia/二、戢佳《借你一扇窗》120x100cm 布面油画 2023年.jpg",
    views: 1350,
    sold: 0,
    stock: 1,
    featured: false,
    charityPct: 40,
  },
  {
    id: 10,
    title: "枣园秋熟",
    aid: 4,
    artist: "戢佳",
    price: 52000,
    orig: null,
    cat: "油画",
    style: "写意油画",
    size: "100×120cm",
    year: "2024",
    mat: "布面油画",
    desc: "以浓郁暖色捕捉秋日丰收景象，传递土地与季节的厚实力量。",
    img: "/artists/jijia/三、戢佳《枣园秋熟》100x120cm 布面油画 2024年.jpg",
    views: 1180,
    sold: 0,
    stock: 1,
    featured: false,
    charityPct: 40,
  },
  {
    id: 11,
    title: "读花观海",
    aid: 5,
    artist: "刘传珂",
    price: 26000,
    orig: null,
    cat: "油画",
    style: "花卉风景",
    size: "40×50cm",
    year: "2025",
    mat: "布面油画",
    desc: "花影与海意在一幅画中相互映照，色彩轻盈而富于诗意。",
    img: "/artists/liuchuanke/刘传珂《读花观海》40×50cm 布面油画.jpg",
    views: 860,
    sold: 0,
    stock: 1,
    featured: true,
    charityPct: 40,
  },
  {
    id: 12,
    title: "绽放",
    aid: 5,
    artist: "刘传珂",
    price: 22000,
    orig: null,
    cat: "油画",
    style: "花卉油画",
    size: "40×40cm",
    year: "2025",
    mat: "布面油画",
    desc: "以开放姿态的花朵为主体，笔触明快，画面充满春日生长感。",
    img: "/artists/liuchuanke/刘传珂《绽放》40×40cm 布面油画.jpg",
    views: 740,
    sold: 0,
    stock: 1,
    featured: false,
    charityPct: 40,
  },
  {
    id: 13,
    title: "海边",
    aid: 6,
    artist: "生辉",
    price: 36000,
    orig: null,
    cat: "油画",
    style: "写意油画",
    size: "60×80cm",
    year: "2024",
    mat: "布面油画",
    desc: "以开放笔意描绘海边光线与空间起伏，展现自然景观的呼吸感。",
    img: "/artists/shenghui/一、生辉《海边》  60x80cm 布面油画 2024年.jpg",
    views: 1440,
    sold: 0,
    stock: 1,
    featured: true,
    charityPct: 40,
  },
  {
    id: 14,
    title: "山水之梦之八",
    aid: 6,
    artist: "生辉",
    price: 24000,
    orig: null,
    cat: "丙烯油画",
    style: "写意风景",
    size: "50×40cm",
    year: "2025",
    mat: "布面丙烯油画",
    desc: "在梦幻般的山水构成中，探索自然与内心景象的交会。",
    img: "/artists/shenghui/二、生辉《山水之梦之八》  50x40cm 布面丙烯油画 2025年.jpg",
    views: 1120,
    sold: 0,
    stock: 1,
    featured: false,
    charityPct: 40,
  },
  {
    id: 15,
    title: "艺甸园的屋顶",
    aid: 6,
    artist: "生辉",
    price: 36000,
    orig: null,
    cat: "油画",
    style: "写意风景",
    size: "60×80cm",
    year: "2024",
    mat: "布面油画",
    desc: "将屋顶、天空与周边环境化作跳跃色块，形成明快节奏。",
    img: "/artists/shenghui/三、生辉《艺甸园的屋顶》  60x80cm 布面油画 2024年.jpg",
    views: 960,
    sold: 0,
    stock: 1,
    featured: false,
    charityPct: 40,
  },
  {
    id: 16,
    title: "惊涛",
    aid: 7,
    artist: "吴良孝",
    price: 32000,
    orig: null,
    cat: "油画",
    style: "海景表现",
    size: "60×80cm",
    year: "2025",
    mat: "布面油画",
    desc: "以翻涌海浪与厚重肌理构成强烈视觉张力，呈现山海之间的力量感。",
    img: "/artists/wuliangxiao/惊涛60X80cm吴良孝2025年.jpg",
    views: 920,
    sold: 0,
    stock: 1,
    featured: true,
    charityPct: 40,
  },
  {
    id: 17,
    title: "秋意",
    aid: 7,
    artist: "吴良孝",
    price: 28000,
    orig: null,
    cat: "油画",
    style: "抒情风景",
    size: "60×80cm",
    year: "2025",
    mat: "布面油画",
    desc: "用沉静色层描绘秋日景致，在温润笔触中传达季节的内省气息。",
    img: "/artists/wuliangxiao/秋意60X80cm吴良孝2025年.jpg",
    views: 760,
    sold: 0,
    stock: 1,
    featured: false,
    charityPct: 40,
  },
  {
    id: 18,
    title: "红色记忆之一",
    aid: 8,
    artist: "吴有才",
    price: 30000,
    orig: null,
    cat: "油画",
    style: "主题创作",
    size: "—",
    year: "2025",
    mat: "布面绘画",
    desc: "资料中收录的主题作品之一，以厚重色彩和叙事构图延续“红色记忆”系列表达。",
    img: "/artists/wuyoucai/二、.png",
    views: 680,
    sold: 0,
    stock: 1,
    featured: false,
    charityPct: 40,
  },
  {
    id: 19,
    title: "红色记忆之二",
    aid: 8,
    artist: "吴有才",
    price: 30000,
    orig: null,
    cat: "油画",
    style: "主题创作",
    size: "—",
    year: "2025",
    mat: "布面绘画",
    desc: "延续人物与历史叙事表达，画面更强调群像氛围与精神力量。",
    img: "/artists/wuyoucai/三、.png",
    views: 640,
    sold: 0,
    stock: 1,
    featured: false,
    charityPct: 40,
  },
  {
    id: 20,
    title: "秋日",
    aid: 9,
    artist: "许丙屯",
    price: 30000,
    orig: null,
    cat: "油画",
    style: "风景油画",
    size: "50×50cm",
    year: "2024",
    mat: "布面油画",
    desc: "用沉稳而明亮的色调表现秋景层次，画面饱含南方自然气息。",
    img: "/artists/xubingtun/一、许丙屯《秋日》50×50cm 布面油画 2024年.JPG",
    views: 1380,
    sold: 0,
    stock: 1,
    featured: true,
    charityPct: 40,
  },
  {
    id: 19,
    title: "秋荷",
    aid: 9,
    artist: "许丙屯",
    price: 30000,
    orig: null,
    cat: "油画",
    style: "风景油画",
    size: "50×50cm",
    year: "2024",
    mat: "布面油画",
    desc: "以简洁构成与温润色层表现荷塘秋意，安静中见力量。",
    img: "/artists/xubingtun/三、许丙屯《秋荷》50×50cm 布面油画 2024年.JPG",
    views: 920,
    sold: 0,
    stock: 1,
    featured: false,
    charityPct: 40,
  },
  {
    id: 20,
    title: "园林一角",
    aid: 10,
    artist: "张昆",
    price: 26000,
    orig: null,
    cat: "油画",
    style: "风景油画",
    size: "40×40cm",
    year: "2025",
    mat: "布面油画",
    desc: "取园林一隅入画，在细腻层次中传达静观自然的闲适意境。",
    img: "/artists/zhangkun/一、园林一角40×40.jpg",
    views: 870,
    sold: 0,
    stock: 1,
    featured: true,
    charityPct: 40,
  },
  {
    id: 21,
    title: "香韵",
    aid: 10,
    artist: "张昆",
    price: 32000,
    orig: null,
    cat: "油画",
    style: "风景油画",
    size: "60×80cm",
    year: "2025",
    mat: "布面油画",
    desc: "花木与空间在柔和色彩中展开，营造温润而富有诗性的氛围。",
    img: "/artists/zhangkun/二、香韵60×80.jpg",
    views: 790,
    sold: 0,
    stock: 1,
    featured: false,
    charityPct: 40,
  },
  {
    id: 22,
    title: "田园锦绣",
    aid: 10,
    artist: "张昆",
    price: 34000,
    orig: null,
    cat: "油画",
    style: "田园风景",
    size: "60×80cm",
    year: "2025",
    mat: "布面油画",
    desc: "以饱满色彩表现田园景观的明媚与丰盛，富有生活温度。",
    img: "/artists/zhangkun/三、田园锦绣60×80.jpg",
    views: 830,
    sold: 0,
    stock: 1,
    featured: false,
    charityPct: 40,
  },
]

export const categories = ["全部", "国画", "油画", "水彩", "雕塑", "摄影", "陶艺"]

export const categoryIcons = {
  全部: "🌟",
  国画: "🎋",
  油画: "🖼️",
  水彩: "🌈",
  雕塑: "🗿",
  摄影: "📷",
  陶艺: "🏺",
}

export const exhibitions = [
  {
    id: 1,
    title: "春季名家精品展",
    type: "线上展览",
    cover: "https://picsum.photos/seed/ex1/800/500",
    artist: "美芽集合作艺术家",
    location: "线上展厅",
    date: "2026-04-20 至 2026-05-20",
    price: 0,
    status: "正在展出",
    tag: "免费参观",
    desc: "汇聚十位合作艺术家的最新代表作，呈现花卉、风景与写意油画等多元面貌。",
    highlights: ["线上观展", "十位艺术家联展", "代表作品集中呈现"],
  },
  {
    id: 2,
    title: "美育公益联展",
    type: "公益展览",
    cover: "https://picsum.photos/seed/ex2/800/500",
    artist: "美芽集公益计划",
    location: "美芽集公益空间",
    date: "2026-05-01 至 2026-06-01",
    price: 0,
    status: "即将开始",
    tag: "公益主题",
    desc: "围绕公益美育与乡村振兴主题，展示艺术家参与公益项目的创作力量。",
    highlights: ["公益主题策展", "乡村美育内容呈现", "艺术共创交流"],
  },
]

export const orders = [
  {
    id: "MYJ20260408001",
    status: "待发货",
    date: "2026-04-08 14:20",
    total: 64000,
    arts: [
      {
        title: "窗前的海棠花",
        artist: "范汇飞",
        price: 28000,
        img: "/artists/fanhuifei/范汇飞《窗前的海棠花》50x60cm 2025年.jpg",
      },
      {
        title: "乐园",
        artist: "郭争光",
        price: 46000,
        img: "/artists/guozhengguang/二、郭争光《乐园》60×80cm   布面油画  2024年.jpg",
      },
    ],
  },
  {
    id: "MYJ20260402002",
    status: "运输中",
    date: "2026-04-02 09:15",
    total: 38000,
    arts: [
      {
        title: "白石清风",
        artist: "戢佳",
        price: 38000,
        img: "/artists/jijia/一、戢佳《白石清风》60x60cm 布面油画 2025年.jpg",
      },
    ],
  },
  {
    id: "MYJ20260326003",
    status: "已完成",
    date: "2026-03-26 16:48",
    total: 30000,
    arts: [
      {
        title: "秋日",
        artist: "许丙屯",
        price: 30000,
        img: "/artists/xubingtun/一、许丙屯《秋日》50×50cm 布面油画 2024年.JPG",
      },
    ],
  },
]

export const charity = [
  {
    id: 1,
    title: "乡村美育教室计划",
    tag: "长期项目",
    cover: "https://picsum.photos/seed/charity1/800/500",
    desc: "联合艺术家与志愿者，为乡村学校建设可持续运转的美育教室与课程体系。",
    raised: 128000,
    beneficiaries: 180,
  },
  {
    id: 2,
    title: "儿童写生活动支持计划",
    tag: "公益活动",
    cover: "https://picsum.photos/seed/charity2/800/500",
    desc: "为偏远地区儿童提供写生工具包、课程支持与线下艺术体验活动。",
    raised: 86000,
    beneficiaries: 96,
  },
]

export const charityActivities = [
  {
    id: 1,
    title: "2024年新萌芽户外公益讲堂第一课——美在永泰",
    tag: "户外公益讲堂",
    date: "2024-05-02",
    location: "福建永泰",
    participants: 60,
    cover: "/charity-articles/yongtai.jpg",
    desc: "以户外讲堂为起点，把艺术体验与乡村自然课堂结合，让孩子们在真实景观中感受色彩、观察与表达。",
  },
  {
    id: 2,
    title: "爱与美的播种：艺术家以美育赋能乡村振兴——美在婺源公益讲堂活动",
    tag: "公益讲堂",
    date: "2023-03-21",
    location: "江西婺源",
    participants: 88,
    cover: "/charity-articles/wuyuan.jpg",
    desc: "新萌芽专项基金联合艺术家走进婺源，以公益讲堂和现场交流把美育带入乡村振兴的日常场景。",
  },
  {
    id: 3,
    title: "美在洽湾——《侨爱心365-乡村美育》户外公益讲堂",
    tag: "乡村美育",
    date: "2023-11-24",
    location: "福建洽湾",
    participants: 72,
    cover: "/charity-articles/qiawan.jpg",
    desc: "围绕《侨爱心365-乡村美育》主题开展户外公益讲堂，让孩子们在开放课堂里接触绘画与审美启蒙。",
  },
  {
    id: 4,
    title: "美在青州——2025年《侨爱心365-乡村美育》户外公益讲堂",
    tag: "年度公益课",
    date: "2025-10-14",
    location: "山东青州",
    participants: 95,
    cover: "/charity-articles/qingzhou.jpg",
    desc: "2025年度公益讲堂落地青州，延续乡村美育实践，通过艺术互动与观察训练提升孩子们的创造力。",
  },
  {
    id: 5,
    title: "美在榕江——美育浸润乡村学校课堂，艺术赋能乡村文化振兴",
    tag: "课堂浸润",
    date: "2023-08-25",
    location: "贵州榕江",
    participants: 84,
    cover: "/charity-articles/rongjiang.jpg",
    desc: "把美育课堂真正带进乡村学校，让艺术教育从一次活动延伸为更长期、更深入的文化陪伴。",
  },
  {
    id: 6,
    title: "美在文山——2025年《侨爱心365-乡村美育》户外公益讲堂",
    tag: "户外公益讲堂",
    date: "2025-04-24",
    location: "云南文山",
    participants: 90,
    cover: "/charity-articles/wenshan-lecture.jpg",
    desc: "以文山在地文化与自然环境为背景，组织艺术家开展户外公益讲堂，增强孩子们的观察与创作兴趣。",
  },
  {
    id: 7,
    title: "美在文山——时代青年油画社公益写生教学系列活动（第六回）圆满结束",
    tag: "写生教学",
    date: "2025-04-21",
    location: "云南文山",
    participants: 68,
    cover: "/charity-articles/wenshan-workshop.jpg",
    desc: "聚焦公益写生教学与现场实践，通过连续课程与互动示范，让乡村孩子获得更具体的绘画体验。",
  },
]

export const stories = [
  {
    id: 1,
    type: "公益回访",
    title: "一间教室如何点亮孩子的第一堂美术课",
    author: "美芽集编辑部",
    read: "1.2k 阅读",
    cover: "https://picsum.photos/seed/story1/300/300",
  },
  {
    id: 2,
    type: "艺术家行动",
    title: "十位合作艺术家共同参与乡村美育共创计划",
    author: "项目组",
    read: "980 阅读",
    cover: "https://picsum.photos/seed/story2/300/300",
  },
]

export const charityArticleDetails = {
  1: {
    title: "2024年新萌芽户外公益讲堂第一课——美在永泰",
    date: "2024年05月02日",
    author: "新萌芽TREE",
    location: "福建永泰",
    tag: "户外公益讲堂",
    cover: "/charity-articles/yongtai.jpg",
    sections: [
      "4月22号，时代青年油画社与中国华侨公益基金会新萌芽专项基金在福建省福州市永泰二中共同开展了2024年首次乡村美育户外公益讲堂活动，活动包括捐赠画材、走访困难学生、写生课堂、师生共绘一幅画、与乡村教师交流业务等。",
      "本次活动共向学校捐赠了46类、1753套（件）画材，总价值六万余元。善款皆是通过去年的活动零零散散向七、八十位新萌芽支持者募集到的，涓涓细流汇成江河，有大家的支持我们才完成了这次活动。",
      "美育是乡村人才振兴的重要路径之一，可以赋能广大乡村学校培养德智体美劳全面发展的优秀人才。2023年时代青年油画社在河北、江西、贵州等地开展公益教学活动的同时，作为艺术团队也主动承担着社会责任，我们通过试点的方式探索出多路径的乡村帮扶办法，形成一系列乡村美育活动，本次福州永泰之行便是2024年的首次美育实践。",
      "参加此次活动的艺术家有：王春华、许丙屯、郭争光、戢佳、吴有才、江哲、陈康康，在活动正式开始前3天就已经到达永泰二中，提前和学校相关部门沟通，准备课程，运输物资，筹备会场等准备工作。活动过程中在校园内开展户外写生、校内墙绘特色课程，在互动交流和公益支教课上，艺术家们手把手教师生们写字与绘画，面对面讲授绘画的原理，用画笔从不同角度展现家乡的美，引导学生们充分发挥想象力、观察力与创造力，共同完成了长30米，高5米的墙绘。墙绘结束后，孩子们告诉我们，他们这两天过得太开心了，希望以后能多些户外写生的机会。",
      "学校课程结束之后，时代青年油画社的艺术家们又和当地老师交流工作，探讨绘画教学的问题。并开展了座谈会，就欠发达地区的美育教学问题进行探讨，两位当地教师对当前面临的困境和需要的资源支持提出了建议。",
      "中国华侨公益基金会及福州县部门相关领导也应邀参加此次活动，并共同走访慰问了两名困难学生，送去书籍等学习用品。",
      "孤举者难起，众行者易趋。今后我们时代青年油画社的艺术家们将汇聚更多力量，推动社会公益事业的发展，愿更多的人来加入我们，一起用艺术助力乡村美育，用爱心托起未来梦想！",
    ],
    images: [
      "/charity-articles/images/article1_1.png",
      "/charity-articles/images/article1_2.png",
      "/charity-articles/images/article1_3.png",
      "/charity-articles/images/article1_4.png",
      "/charity-articles/images/article1_5.png",
    ],
  },
  2: {
    title: "爱与美的播种——美在婺源公益讲堂活动",
    date: "2023年03月21日",
    author: "时代青年油画社",
    location: "江西婺源",
    tag: "公益讲堂",
    cover: "/charity-articles/wuyuan.jpg",
    sections: [
      "阳春三月，中国华侨公益基金会新萌芽专项基金联合时代青年油画社走进江西婺源，开展《美在婺源》公益讲堂活动。艺术家们以美育为纽带，将艺术的种子播撒在这片充满诗意的土地上。",
      "本次活动以《爱与美的播种》为主题，通过公益讲座、现场示范、互动体验等形式，让乡村孩子近距离感受艺术的魅力。画家们在婺源的徽派建筑与油菜花海间开展写生创作，同时为当地师生带来生动的美术课堂。",
      "参与活动的艺术家们纷纷表示，能够用自己的专业所长为乡村美育贡献力量，是一件非常有意义的事情。艺术不分地域，每个孩子都应该拥有接触美、发现美、创造美的机会。",
      "活动中还向当地学校捐赠了一批优质画材和学习用品，希望能够为学校的日常美术教学提供实实在在的支持。我们相信，持续的美育投入终将开花结果。",
    ],
    images: [
      "/charity-articles/images/article2_1.jpg",
      "/charity-articles/images/article2_2.jpg",
      "/charity-articles/images/article2_3.jpg",
      "/charity-articles/images/article2_4.jpg",
      "/charity-articles/images/article2_5.jpg",
      "/charity-articles/images/article2_6.jpg",
      "/charity-articles/images/article2_7.jpg",
      "/charity-articles/images/article2_8.jpg",
      "/charity-articles/images/article2_9.jpg",
      "/charity-articles/images/article2_10.jpg",
      "/charity-articles/images/article2_11.jpg",
      "/charity-articles/images/article2_12.jpg",
      "/charity-articles/images/article2_13.jpg",
    ],
  },
  3: {
    title: "美在洽湾——《侨爱心365-乡村美育》户外公益讲堂",
    date: "2023年11月24日",
    author: "时代青年油画社",
    location: "江西南丰洽湾",
    tag: "乡村美育",
    cover: "/charity-articles/qiawan.jpg",
    sections: [
      "江西南丰历史悠久，素有千年古邑、飞城走塔、耕读传家的美名，更是唐宋八大家曾巩的故里。",
      "2023年11月15日，中国华侨公益基金会新萌芽专项基金联合时代青年油画社在江西省抚州市南丰县洽湾镇举办第五期乡村美育公益活动——《侨爱心365·美在洽湾》。油画社的艺术家为洽湾小学70名学生开展了公益美育课堂，并为全校173名学生捐赠了画材物资。",
      "参加这次活动的艺术家有：吴良孝、陈康康、王春华、许丙屯、戢茹嘉、刘传珂、郭争光、吴有才、生辉、陈燕仁。",
      "在活动前期，新萌芽专项基金和时代青年油画社的代表们与洽湾镇中心小学的校长进行了座谈，并对学校的情况进行了深入了解：学校在校生共有173人，一半以上的学生是留守儿童，师资配备方面艺术类教师极其匮乏，目前全校是由一名语文老师代艺术课程。",
      "画家们经过在镇上考察与交流后多次开会讨论，最终确定好了上课方案和物资准备。",
      "次日，艺术家团队首先带领学生们在户外写生。写生前几位画家分别就建筑特征及周边环境给大家做了讲解，引导孩子们用画笔尽情表达自己的所思所想。学生们积极认真，敢于创作，对户外写生充满了极高的热情。",
      "随后开展的特色课程环节中，艺术家们通过示范和一对一指导，让孩子们体验了从观察到落笔的完整过程。看到孩子们专注的眼神和完成作品后的笑容，所有付出的努力都变得值得。",
    ],
    images: [
      "/charity-articles/images/article3_1.jpg",
      "/charity-articles/images/article3_2.jpg",
      "/charity-articles/images/article3_3.jpg",
      "/charity-articles/images/article3_4.jpg",
      "/charity-articles/images/article3_5.jpg",
      "/charity-articles/images/article3_6.jpg",
      "/charity-articles/images/article3_7.jpg",
      "/charity-articles/images/article3_8.jpg",
      "/charity-articles/images/article3_9.jpg",
      "/charity-articles/images/article3_10.jpg",
      "/charity-articles/images/article3_11.jpg",
      "/charity-articles/images/article3_12.jpg",
      "/charity-articles/images/article3_13.png",
      "/charity-articles/images/article3_14.jpg",
      "/charity-articles/images/article3_15.jpg",
    ],
  },
  4: {
    title: "美在青州——2025年《侨爱心365-乡村美育》户外公益讲堂",
    date: "2025年10月14日",
    author: "时代青年油画社",
    location: "山东青州",
    tag: "年度公益课",
    cover: "/charity-articles/qingzhou.jpg",
    sections: [
      "2025年10月11日，由中国华侨公益基金会、山东省侨联主办，中国华侨公益基金会新萌芽专项基金、时代青年油画社承办，青州市侨联、青州市云门山回民学校、青州美术馆、青州市油画学会协办的《美在青州—2025年侨爱心365-乡村美育户外公益讲堂》艺术活动在云门山回民学校举办。",
      "本次活动以《美在青州》为主题，通过画材捐赠、户外写生课堂、学生走访、师生共绘一幅画、写生示范、座谈交流等形式，为当地师生带去丰富的美育体验，助力乡村美育发展，以艺术为媒介传递爱心，充分发挥美育在乡村教育中的滋养作用。",
      "出席本次活动的嘉宾有：中国华侨公益基金会新萌芽专项基金理事姜灿，青州市教育教学研究院院长杨玉昌，新萌芽专项基金项目主任陈康，以及青州市相关部门负责同志。",
      "参加本次活动的画家有：中国美术家协会会员吴良孝；中国美术家协会会员吴有才；中国美术家协会会员陈淑敏；北京当代写意油画研究院创作员范汇飞；山东省美术家协会会员生辉；以及青州市油画学会的公益志愿者们。",
      "10月11日上午，中国华侨公益基金会新萌芽专项基金向青州市云门山回民学校捐赠了各类画材，为乡村美育提供硬件支持。",
      "10月12日上午，时代青年油画社画家在青州古城与学校美术教师及当地油画学会同道们开展写生交流活动，相互分享创作心得和理念。",
      "10月12日下午，画家们在青州油画院同学校美术教师及当地油画学会同道们开展了《美在青州》交流座谈会，共同讨论如何提升美育教学质量。",
      "我们希望通过持续的美育行动，让乡村孩子也能享有优质的艺术教育。未来，我们将继续深化民族美育深耕计划，推动城乡美育资源联动，让艺术的种子在更多乡村生根发芽。",
    ],
    images: [
      "/charity-articles/images/article4_1.png",
      "/charity-articles/images/article4_2.png",
      "/charity-articles/images/article4_3.jpg",
      "/charity-articles/images/article4_4.png",
      "/charity-articles/images/article4_5.jpg",
      "/charity-articles/images/article4_6.jpg",
      "/charity-articles/images/article4_7.jpg",
      "/charity-articles/images/article4_8.png",
      "/charity-articles/images/article4_9.png",
      "/charity-articles/images/article4_10.jpg",
      "/charity-articles/images/article4_11.jpg",
      "/charity-articles/images/article4_12.jpg",
      "/charity-articles/images/article4_13.jpg",
      "/charity-articles/images/article4_14.jpg",
      "/charity-articles/images/article4_15.jpg",
    ],
  },
  5: {
    title: "美在榕江——美育浸润乡村学校课堂，艺术赋能乡村文化振兴",
    date: "2023年08月25日",
    author: "时代青年油画社",
    location: "贵州榕江",
    tag: "课堂浸润",
    cover: "/charity-articles/rongjiang.jpg",
    sections: [
      "贵州省黔东南苗族侗族自治州榕江县，这片被群山环抱的土地上，有一群热爱艺术的乡村孩子。他们渴望着专业的美术指导，期待着用画笔描绘家乡的山山水水。",
      "2023年8月，时代青年油画社携手中国华侨公益基金会新萌芽专项基金走进榕江，把美育课堂真正带进乡村学校。这不是一次性的展示活动，而是希望将艺术教育的火种留在当地，让美育从一次活动延伸为更长期、更深入的文化陪伴。",
      "活动期间，艺术家们深入榕江的多所乡村学校，了解当地美育教学的实际困境。面对师资匮乏、器材不足的现状，大家更加坚定了持续帮扶的决心。",
      "通过现场授课、作品点评、创作指导等多种形式，艺术家们让乡村孩子体验到完整的艺术学习过程。许多孩子是第一次有机会接受专业画家的面对面指导，眼中满是好奇与欣喜。",
      "除了课堂教学，活动还包括向学校捐赠美术用品、与当地教师座谈交流等内容。我们希望通过授人以渔的方式，帮助提升本地教师的美术教学能力，留下带不走的美术教育资源。",
    ],
    images: [
      "/charity-articles/images/article5_1.jpg",
      "/charity-articles/images/article5_2.jpg",
      "/charity-articles/images/article5_3.jpg",
      "/charity-articles/images/article5_4.jpg",
      "/charity-articles/images/article5_5.jpg",
      "/charity-articles/images/article5_6.jpg",
      "/charity-articles/images/article5_7.jpg",
      "/charity-articles/images/article5_8.jpg",
      "/charity-articles/images/article5_9.jpg",
      "/charity-articles/images/article5_10.jpg",
      "/charity-articles/images/article5_11.jpg",
    ],
  },
  6: {
    title: "美在文山——2025年《侨爱心365-乡村美育》户外公益讲堂",
    date: "2025年04月24日",
    author: "时代青年油画社",
    location: "云南文山",
    tag: "户外公益讲堂",
    cover: "/charity-articles/wenshan-lecture.jpg",
    sections: [
      "云南文山，这片位于祖国西南边陲的美丽土地，以其独特的喀斯特地貌和多民族文化而闻名。2025年4月，时代青年油画社再次出发，在这里开启了新一年的乡村美育实践。",
      "由中国华侨公益基金会新萌芽专项基金主办的《美在文山—2025年侨爱心365-乡村美育户外公益讲堂》，以文山在地文化与自然环境为背景，组织艺术家开展户外公益讲堂，增强孩子们的观察与创作兴趣。",
      "活动选址于文山的乡村学校，这里的孩子大多来自少数民族家庭，有着与生俱来的色彩感和对美的朴素感知。艺术家们因势利导，将当地的民族元素融入教学内容，让孩子们用熟悉的视角去重新审视身边的世界。",
      "课堂上，画家们带领学生走出教室，在真实的自然景观中进行观察和写生。从构图到配色，从光影到笔触，每一个知识点都结合眼前的具体景物来讲解，让抽象的艺术概念变得可感可知。",
      "除了写生训练，活动还安排了师生共绘长卷的集体创作环节。巨大的画布铺展在操场上，孩子们与艺术家并肩执笔，共同描绘心中的美丽家园。这种协作式的艺术体验，不仅锻炼了绘画技能，更培养了团队精神和集体荣誉感。",
      "活动最后，所有参与的学生都收到了专属的画具礼包，希望这份礼物能够陪伴他们在艺术的道路上继续前行。",
    ],
    images: [
      "/charity-articles/images/article6_1.jpg",
      "/charity-articles/images/article6_2.jpg",
      "/charity-articles/images/article6_3.jpg",
      "/charity-articles/images/article6_4.jpg",
      "/charity-articles/images/article6_5.jpg",
      "/charity-articles/images/article6_6.jpg",
      "/charity-articles/images/article6_7.jpg",
      "/charity-articles/images/article6_8.jpg",
      "/charity-articles/images/article6_9.jpg",
      "/charity-articles/images/article6_10.jpg",
      "/charity-articles/images/article6_11.jpg",
      "/charity-articles/images/article6_12.jpg",
      "/charity-articles/images/article6_13.jpg",
      "/charity-articles/images/article6_14.jpg",
      "/charity-articles/images/article6_15.jpg",
    ],
  },
  7: {
    title: "美在文山——时代青年油画社公益写生教学系列活动（第六回）圆满结束",
    date: "2025年04月21日",
    author: "时代青年油画社",
    location: "云南文山",
    tag: "写生教学",
    cover: "/charity-articles/wenshan-workshop.jpg",
    sections: [
      "继户外公益讲堂之后，时代青年油画社在云南文山继续推进公益写生教学系列活动第六回。这是一次聚焦深度教学与实践的创作型公益活动，旨在让乡村孩子获得更系统、更具体的绘画体验。",
      "与前期的普及性美育活动不同，写生教学系列更强调技法的传授和创作的引导。参与活动的学生在之前的公益讲堂中已展现出浓厚的兴趣和对艺术的敏感度，本次活动为他们提供了进一步深造的机会。",
      "活动内容涵盖风景写生、静物组合、人物速写等多个板块。每位艺术家负责一个小组，进行小班化的精细指导。从取景构图到调色技法，从线条运用到画面处理，孩子们在反复练习中逐步掌握了基本要领。",
      "值得一提的是，本次活动中有多位学生完成了人生中的第一幅完整写生作品。当这些稚嫩却真诚的作品被展示出来时，在场的所有人都深受感动。艺术的价值不仅在于技巧的高度，更在于表达的真诚。",
      "活动尾声举办了小型作品汇报展，学生们的画作被精心装裱后陈列展出。当地学校领导和家长们受邀参观，看着孩子们的作品，许多人眼眶湿润。这些画作不仅是学习的成果，更是乡村孩子自信心的见证。",
      "时代青年油画社表示，写生教学系列活动将持续举办，希望通过年复一年的坚持，在更多乡村孩子心中种下艺术的种子，静待花开的那一天。",
    ],
    images: [
      "/charity-articles/images/article7_1.jpg",
      "/charity-articles/images/article7_2.jpg",
      "/charity-articles/images/article7_3.jpg",
      "/charity-articles/images/article7_4.jpg",
      "/charity-articles/images/article7_5.jpg",
      "/charity-articles/images/article7_6.jpg",
      "/charity-articles/images/article7_7.jpg",
      "/charity-articles/images/article7_8.jpg",
      "/charity-articles/images/article7_9.jpg",
      "/charity-articles/images/article7_10.jpg",
      "/charity-articles/images/article7_11.jpg",
      "/charity-articles/images/article7_12.jpg",
      "/charity-articles/images/article7_13.jpg",
      "/charity-articles/images/article7_14.jpg",
      "/charity-articles/images/article7_15.jpg",
    ],
  },
}

export const events = [
  {
    id: 1,
    title: "艺术家面对面：春季联展分享会",
    type: "艺术沙龙",
    cover: "https://picsum.photos/seed/ev1/800/400",
    date: "2026-04-20 14:00",
    location: "美芽集艺术中心",
    participants: 86,
    price: 0,
    status: "报名中",
    tag: "公益免费",
    desc: "围绕本季合作艺术家作品展开导览与交流，现场开放提问与收藏咨询。",
  },
  {
    id: 2,
    title: "儿童水墨体验工作坊",
    type: "公益活动",
    cover: "https://picsum.photos/seed/ev2/800/400",
    date: "2026-04-25 10:00",
    location: "美芽集公益空间",
    participants: 45,
    price: 0,
    status: "报名中",
    tag: "亲子活动",
    desc: "面向亲子家庭开放的公益体验课，让孩子在轻松氛围中感受艺术表达。",
  },
]
